// Datos técnicos de la Suzuki GSX-R 600 K6 (2006-2007).
// Basados en el plan de mantenimiento periódico y especificaciones del manual de servicio.
// Verifica siempre los valores críticos con el manual de taller de tu unidad.

const BIKE = {
  name: 'Suzuki GSX-R 600 K6',
  years: '2006 – 2007',
  specs: [
    { label: 'Aceite motor', value: 'SAE 10W-40, API SG o superior, JASO MA' },
    { label: 'Capacidad aceite', value: '3,0 L (cambio) · 3,3 L (con filtro) · 3,9 L (en seco)' },
    { label: 'Bujías', value: 'NGK CR9EIA-9 · distancia 0,8–0,9 mm' },
    { label: 'Refrigerante', value: 'Anticongelante 50 % · aprox. 2,4 L' },
    { label: 'Líquido de frenos', value: 'DOT 4' },
    { label: 'Holgura válvulas (frío)', value: 'Admisión 0,08–0,18 mm · Escape 0,18–0,28 mm' },
    { label: 'Holgura cadena', value: '20–30 mm (moto en caballete lateral)' },
    { label: 'Cadena', value: 'RK GB50GSVZ3 · 114 eslabones · paso 530' },
    { label: 'Presión neumáticos', value: 'Delantero 2,5 bar · Trasero 2,9 bar (en frío)' },
    { label: 'Neumáticos', value: '120/70 ZR17 · 180/55 ZR17' },
    { label: 'Ralentí', value: '1.200 – 1.400 rpm' },
    { label: 'Juego puño gas', value: '2,0 – 4,0 mm' },
    { label: 'Juego maneta embrague', value: '10 – 15 mm' },
  ],
};

// Categorías para agrupar y colorear
const CATEGORIES = {
  motor: { label: 'Motor', color: '#3b82f6' },
  transmision: { label: 'Transmisión', color: '#f59e0b' },
  frenos: { label: 'Frenos', color: '#ef4444' },
  chasis: { label: 'Chasis', color: '#10b981' },
  refrigeracion: { label: 'Refrigeración', color: '#06b6d4' },
  electrico: { label: 'Eléctrico', color: '#a855f7' },
};

// km: intervalo en kilómetros (null = sólo por tiempo)
// months: intervalo en meses (null = sólo por km)
// first: primera revisión en km si difiere del intervalo (rodaje)
// resets: al hacer esta tarea se da por hecha también la indicada
const TASKS = [
  {
    id: 'aceite',
    name: 'Cambio de aceite motor',
    category: 'motor',
    km: 6000,
    months: 12,
    first: 1000,
    duration: '30 min',
    difficulty: 1,
    tools: [
      'Vaso o llave de 17 mm (tapón de vaciado)',
      'Llave dinamométrica (rango 10–60 N·m)',
      'Bandeja de vaciado (mín. 4 L)',
      'Arandela de cobre nueva para el tapón',
      'Embudo',
      'Guantes y trapos',
    ],
    parts: ['3,0 L de aceite 10W-40 JASO MA (3,3 L si cambias filtro)', 'Arandela tapón de vaciado'],
    torques: [
      { part: 'Tapón de vaciado de aceite', nm: 23 },
    ],
    steps: [
      'Arranca el motor y déjalo al ralentí 2–3 minutos para calentar el aceite (fluye mejor). Apágalo.',
      'Coloca la moto recta (caballete trasero de taller) y la bandeja bajo el cárter.',
      'Quita el tapón de llenado de la tapa del embrague para que entre aire y el aceite salga más rápido.',
      'Afloja el tapón de vaciado (17 mm) en la parte inferior del cárter. Cuidado: el aceite sale caliente.',
      'Deja escurrir al menos 10 minutos. Limpia el tapón y revisa si hay limaduras metálicas en el imán/rosca.',
      'Monta el tapón con arandela NUEVA y apriétalo a 23 N·m. No te pases: la rosca es en aluminio.',
      'Si toca, cambia ahora el filtro de aceite (ver tarea "Filtro de aceite").',
      'Rellena con 3,0 L de aceite (3,3 L si has cambiado filtro). Coloca el tapón de llenado.',
      'Arranca 3 minutos, apaga, espera 3 minutos y comprueba el nivel en la mirilla con la moto vertical: entre las marcas F y L.',
      'Revisa que no haya fugas alrededor del tapón y el filtro.',
    ],
    tips: 'Recicla el aceite usado en un punto limpio. Muchos propietarios cambian el filtro en cada cambio de aceite: es barato y recomendable.',
  },
  {
    id: 'filtro-aceite',
    name: 'Cambio filtro de aceite',
    category: 'motor',
    km: 18000,
    months: null,
    first: 1000,
    duration: '15 min (junto con el aceite)',
    difficulty: 1,
    tools: [
      'Llave de filtro de copa 64 mm / 14 caras (o de cinta)',
      'Llave dinamométrica',
      'Trapos (el filtro gotea al sacarlo)',
    ],
    parts: ['Filtro de aceite (Suzuki 16510-07J00, HF138 o equivalente)'],
    torques: [
      { part: 'Filtro de aceite', nm: 20, note: 'o 2 vueltas a mano tras hacer contacto la junta' },
    ],
    steps: [
      'Realiza este paso con el aceite ya vaciado.',
      'Coloca trapos bajo el filtro (está en la parte delantera del cárter, tras el escape).',
      'Afloja el filtro con la llave de copa y termina de quitarlo a mano.',
      'Limpia la superficie de apoyo en el motor.',
      'Unta la junta tórica del filtro nuevo con una película de aceite limpio.',
      'Enrosca a mano hasta que la junta toque la superficie, y luego 2 vueltas más con la llave (≈ 20 N·m).',
      'Rellena de aceite (3,3 L) y comprueba nivel y fugas.',
    ],
    tips: 'El manual marca 18.000 km, pero cambiarlo en cada cambio de aceite alarga la vida del motor.',
  },
  {
    id: 'filtro-aire-limpiar',
    name: 'Filtro de aire: limpiar',
    category: 'motor',
    km: 6000,
    months: null,
    duration: '45 min',
    difficulty: 2,
    tools: [
      'Llave Allen/vaso de 5 y 6 mm (tornillos del depósito)',
      'Destornillador de estrella (tapa de la caja de filtro)',
      'Aire comprimido (opcional)',
    ],
    parts: [],
    torques: [
      { part: 'Tornillos tapa caja de filtro', nm: 3, note: 'apriete suave, rosca en plástico' },
      { part: 'Tornillo trasero del depósito', nm: 10 },
    ],
    steps: [
      'Quita el asiento del piloto.',
      'Retira los tornillos delanteros del depósito y el perno trasero de la bisagra. Levanta el depósito y sujétalo (o desconéctalo con cuidado si vas a retirarlo).',
      'Quita los tornillos de la tapa de la caja del filtro y saca el elemento.',
      'Limpia el filtro de papel golpeándolo suavemente o soplando con aire comprimido DESDE DENTRO hacia fuera (del lado limpio al sucio).',
      'Revisa que no esté roto ni aceitado. Si está muy sucio o dañado, sustitúyelo.',
      'Limpia el interior de la caja con un trapo, sin dejar suciedad hacia las admisiones.',
      'Monta el filtro, cierra la tapa y baja el depósito comprobando que no pillas manguitos ni cables.',
    ],
    tips: 'Si ruedas en zonas de mucho polvo, limpia el filtro con más frecuencia.',
  },
  {
    id: 'filtro-aire-cambiar',
    name: 'Filtro de aire: sustituir',
    category: 'motor',
    km: 18000,
    months: null,
    resets: ['filtro-aire-limpiar'],
    duration: '45 min',
    difficulty: 2,
    tools: [
      'Llave Allen/vaso de 5 y 6 mm',
      'Destornillador de estrella',
    ],
    parts: ['Filtro de aire (Suzuki 13780-01H00, HFA3616 o equivalente)'],
    torques: [
      { part: 'Tornillos tapa caja de filtro', nm: 3, note: 'apriete suave' },
      { part: 'Tornillo trasero del depósito', nm: 10 },
    ],
    steps: [
      'Sigue los mismos pasos que en "Filtro de aire: limpiar" para acceder a la caja.',
      'Sustituye el elemento por uno nuevo. Comprueba que asienta bien en todo su contorno (sin holguras por donde pase aire sin filtrar).',
      'Cierra la tapa y monta el depósito.',
    ],
    tips: '',
  },
  {
    id: 'bujias-revisar',
    name: 'Bujías: inspeccionar',
    category: 'electrico',
    km: 6000,
    months: null,
    duration: '1 h 30 min',
    difficulty: 3,
    tools: [
      'Llave de bujías de 16 mm de pared fina (la de la moto sirve)',
      'Alargo largo + articulación',
      'Galgas de espesores',
      'Cepillo de alambre suave',
      'Llave dinamométrica',
    ],
    parts: [],
    torques: [
      { part: 'Bujías', nm: 11 },
    ],
    steps: [
      'Con el motor FRÍO, levanta o retira el depósito y la caja del filtro de aire para acceder a las bobinas.',
      'Desconecta el conector de cada bobina tipo lápiz y extráela tirando recto hacia arriba (sin girar bruscamente).',
      'Sopla con aire comprimido alrededor de los pozos de bujía antes de quitarlas para que no caiga suciedad al cilindro.',
      'Desenrosca las bujías con la llave de 16 mm.',
      'Revisa el color del electrodo: marrón claro = correcto; negro/hollín = mezcla rica; blanco = mezcla pobre o sobrecalentamiento.',
      'Comprueba la distancia entre electrodos con galgas: 0,8–0,9 mm.',
      'Rosca las bujías a mano primero para no cruzar la rosca y aprieta a 11 N·m.',
      'Monta las bobinas asegurando que entran hasta el fondo y conecta los conectores.',
    ],
    tips: 'Las bujías de iridio no se deben cepillar con fuerza ni ajustar la distancia. Si están mal, sustitúyelas.',
  },
  {
    id: 'bujias-cambiar',
    name: 'Bujías: sustituir',
    category: 'electrico',
    km: 12000,
    months: null,
    resets: ['bujias-revisar'],
    duration: '1 h 30 min',
    difficulty: 3,
    tools: [
      'Llave de bujías de 16 mm de pared fina',
      'Alargo largo + articulación',
      'Llave dinamométrica',
    ],
    parts: ['4 × NGK CR9EIA-9'],
    torques: [
      { part: 'Bujías', nm: 11 },
    ],
    steps: [
      'Accede a las bobinas como en "Bujías: inspeccionar" (motor frío).',
      'Sopla alrededor de los pozos, retira bobinas y bujías viejas.',
      'Comprueba la distancia de las nuevas (0,8–0,9 mm), sin forzar el electrodo de iridio.',
      'Rosca a mano y aprieta a 11 N·m.',
      'Monta bobinas, conectores, caja de filtro y depósito.',
    ],
    tips: '',
  },
  {
    id: 'cadena-engrasar',
    name: 'Cadena: limpiar y engrasar',
    category: 'transmision',
    km: 1000,
    months: null,
    duration: '20 min',
    difficulty: 1,
    tools: [
      'Caballete trasero de taller',
      'Cepillo de cadena de 3 caras',
      'Limpiador de cadenas (o queroseno). Nunca gasolina ni agua a presión',
      'Grasa/spray de cadena apta para juntas O/X-ring',
      'Trapos',
    ],
    parts: [],
    torques: [],
    steps: [
      'Sube la moto al caballete trasero y engrana punto muerto.',
      'Aplica limpiador y frota con el cepillo girando la rueda a mano (NUNCA con el motor en marcha).',
      'Seca bien la cadena con un trapo.',
      'Aplica el lubricante en la parte interior de la cadena (lado de los rodillos), sobre las juntas tóricas.',
      'Deja actuar 10–15 minutos antes de rodar para que no salpique, y limpia el exceso de la llanta.',
    ],
    tips: 'Engrasa también después de rodar con lluvia. Una cadena bien cuidada dura más del doble.',
  },
  {
    id: 'cadena-tensar',
    name: 'Cadena: revisar y tensar',
    category: 'transmision',
    km: 6000,
    months: null,
    first: 1000,
    duration: '30 min',
    difficulty: 2,
    tools: [
      'Vaso de 27 mm para la tuerca del eje trasero (compruébalo en tu unidad)',
      'Llave fija de 12 mm (contratuercas tensores) y de 10 mm (tensores)',
      'Llave dinamométrica (hasta 100 N·m)',
      'Regla o metro',
      'Pasador de aletas nuevo (si tu tuerca lo lleva)',
    ],
    parts: [],
    torques: [
      { part: 'Tuerca eje trasero', nm: 100 },
      { part: 'Contratuercas de los tensores', nm: 23 },
      { part: 'Tuercas corona trasera', nm: 60 },
      { part: 'Tuerca piñón de ataque', nm: 115 },
    ],
    steps: [
      'Con la moto en el caballete lateral, mide la holgura en el punto medio entre piñón y corona: 20–30 mm de recorrido total arriba/abajo.',
      'Gira la rueda y mide en varios puntos: ajusta en el punto más tenso.',
      'Revisa desgaste de piñón y corona (dientes en forma de gancho) y que ningún eslabón esté agarrotado.',
      'Si hay que tensar: sube la moto al caballete trasero y afloja la tuerca del eje trasero.',
      'Afloja las contratuercas y gira los tensores de ambos lados LA MISMA cantidad (usa las marcas del basculante para mantener la rueda alineada).',
      'Baja a caballete lateral y vuelve a medir la holgura (20–30 mm).',
      'Aprieta la tuerca del eje trasero a 100 N·m y las contratuercas a 23 N·m.',
      'Comprueba de nuevo la holgura: al apretar el eje puede variar ligeramente.',
    ],
    tips: 'Mide la cadena: si 21 pasadores (20 pasos) superan 319,4 mm, la cadena está gastada y hay que cambiar el kit completo (cadena, piñón y corona).',
  },
  {
    id: 'frenos-revisar',
    name: 'Frenos: pastillas y discos',
    category: 'frenos',
    km: 6000,
    months: null,
    first: 1000,
    duration: '30 min',
    difficulty: 2,
    tools: [
      'Linterna',
      'Llave Allen/vaso para los tornillos de pinza (compruébalo en tu unidad)',
      'Llave dinamométrica',
      'Calibre o micrómetro (espesor de discos)',
      'Limpiador de frenos',
    ],
    parts: ['Pastillas (si están bajo el límite)'],
    torques: [
      { part: 'Tornillos pinza delantera (anclaje radial)', nm: 35 },
      { part: 'Tornillos pinza trasera', nm: 22 },
      { part: 'Pasador de pastillas', nm: 15 },
      { part: 'Tornillos disco delantero', nm: 23 },
      { part: 'Tornillos disco trasero', nm: 35 },
      { part: 'Tornillo banjo latiguillo', nm: 23 },
    ],
    steps: [
      'Mira las pastillas desde atrás/abajo de cada pinza: si alguna llega a la ranura de desgaste o tiene menos de 1,5 mm de material, cámbialas por juegos completos.',
      'Revisa los discos: sin grietas ni rayas profundas. Espesor mínimo: delantero 4,5 mm, trasero 4,5 mm.',
      'Para cambiar pastillas: quita la tapa/pasador de pastillas, retira las viejas y empuja los pistones con cuidado (vigila que no rebose el depósito de líquido).',
      'Limpia la pinza con limpiador de frenos, monta las pastillas nuevas y el pasador (15 N·m).',
      'Si desmontas pinzas, aprieta: delanteras 35 N·m, trasera 22 N·m.',
      'Bombea la maneta/pedal varias veces antes de mover la moto hasta que el freno se endurezca.',
      'Rueda con suavidad los primeros 200 km para asentar las pastillas.',
    ],
    tips: 'Usa fijador de roscas medio en los tornillos de disco si se desmontan.',
  },
  {
    id: 'liquido-frenos',
    name: 'Líquido de frenos: sustituir',
    category: 'frenos',
    km: null,
    months: 24,
    duration: '1 h',
    difficulty: 3,
    tools: [
      'Llave de 8 mm para purgadores (anillo mejor que fija)',
      'Tubo transparente y bote de recogida',
      'Destornillador de estrella (tapas de depósitos)',
      'Llave dinamométrica',
      'Trapos (el líquido de frenos daña la pintura)',
    ],
    parts: ['500 ml de líquido DOT 4 de envase nuevo'],
    torques: [
      { part: 'Purgadores de pinza', nm: 7.5 },
      { part: 'Tornillos tapa depósito', nm: 1.5, note: 'apriete muy suave' },
    ],
    steps: [
      'Protege depósito, carenado y depósito de gasolina con trapos. El líquido DOT 4 es corrosivo para la pintura.',
      'Abre la tapa del depósito del freno delantero con el manillar recto (depósito horizontal).',
      'Coloca el tubo en el purgador de la pinza más alejada y el otro extremo en el bote.',
      'Aprieta la maneta, abre el purgador 1/4 de vuelta, cierra y suelta la maneta. Repite.',
      'Ve rellenando el depósito con líquido nuevo: nunca debe bajar del mínimo (entraría aire).',
      'Repite hasta que salga líquido limpio y sin burbujas. Luego haz la otra pinza.',
      'Aprieta purgadores a 7,5 N·m, nivela el depósito y cierra la tapa.',
      'Repite el proceso con el freno trasero.',
      'Comprueba que maneta y pedal estén firmes antes de circular.',
    ],
    tips: 'El líquido de frenos absorbe humedad con el tiempo: aunque hagas pocos km, cámbialo cada 2 años.',
  },
  {
    id: 'refrigerante',
    name: 'Refrigerante: sustituir',
    category: 'refrigeracion',
    km: null,
    months: 24,
    duration: '1 h',
    difficulty: 3,
    tools: [
      'Llave de 8 mm / Allen (tornillo de vaciado de la bomba de agua)',
      'Bandeja de vaciado',
      'Embudo',
      'Llave dinamométrica',
    ],
    parts: ['Aprox. 2,4 L de anticongelante 50 % (para motores de aluminio, sin silicatos)', 'Arandela del tornillo de vaciado'],
    torques: [
      { part: 'Tornillo de vaciado de refrigerante', nm: 13 },
      { part: 'Tornillo purgador de aire', nm: 13 },
    ],
    steps: [
      'Hazlo SIEMPRE con el motor frío: el sistema está a presión.',
      'Quita el carenado lateral necesario para acceder al tapón del radiador y al vaso de expansión.',
      'Retira el tapón del radiador.',
      'Afloja el tornillo de vaciado de la bomba de agua y deja caer todo el refrigerante en la bandeja.',
      'Vacía también el vaso de expansión.',
      'Monta el tornillo de vaciado con arandela nueva (13 N·m).',
      'Llena lentamente por el radiador hasta la boca. Mueve suavemente los manguitos para purgar el aire.',
      'Arranca el motor al ralentí con el tapón quitado, rellenando mientras bajan las burbujas.',
      'Pon el tapón del radiador, llena el vaso de expansión hasta la marca F y revisa el nivel tras la primera salida.',
    ],
    tips: 'El refrigerante es tóxico y dulce: mantenlo lejos de mascotas y llévalo a un punto limpio.',
  },
  {
    id: 'manguitos',
    name: 'Manguitos (radiador y gasolina)',
    category: 'refrigeracion',
    km: 6000,
    months: null,
    duration: '15 min',
    difficulty: 1,
    tools: ['Linterna', 'Destornillador (abrazaderas)'],
    parts: [],
    torques: [],
    steps: [
      'Revisa todos los manguitos del radiador: sin grietas, abombamientos ni pérdidas en las abrazaderas.',
      'Comprueba el nivel del vaso de expansión con el motor frío (entre L y F).',
      'Revisa el manguito de gasolina: sin grietas ni olor a gasolina.',
      'Limpia el panal del radiador de insectos (con agua a baja presión, desde detrás).',
    ],
    tips: 'Los manguitos de gasolina se deben sustituir cada 4 años aunque parezcan en buen estado.',
  },
  {
    id: 'valvulas',
    name: 'Holgura de válvulas',
    category: 'motor',
    km: 24000,
    months: null,
    duration: '4–6 h',
    difficulty: 5,
    tools: [
      'Galgas de espesores (0,05–0,35 mm)',
      'Vaso de 8 mm y 10 mm (tapa de balancines)',
      'Llave de 17 mm o Allen para girar el cigüeñal (tapa del generador/sensor)',
      'Micrómetro (para medir pastillas de reglaje)',
      'Llave dinamométrica de rango bajo (5–25 N·m)',
      'Imán telescópico',
    ],
    parts: ['Junta de la tapa de balancines', 'Pastillas de reglaje según medición'],
    torques: [
      { part: 'Tornillos tapa de balancines', nm: 14 },
      { part: 'Tornillos soportes de árbol de levas', nm: 10 },
      { part: 'Tornillo tensor de cadena de distribución', nm: 10 },
      { part: 'Tapa de inspección del cigüeñal', nm: 11 },
      { part: 'Bujías', nm: 11 },
    ],
    steps: [
      'Motor completamente FRÍO. Retira asiento, depósito, caja de filtro, bobinas y bujías.',
      'Quita la tapa de balancines (tornillos en cruz, de fuera hacia dentro).',
      'Quita la tapa de inspección del cigüeñal y gira el motor en su sentido normal hasta el PMS indicado por las marcas.',
      'Mide con galgas la holgura de las válvulas indicadas por la posición de los lóbulos (las que no están pisadas por la leva). Gira 360° para medir el resto.',
      'Valores correctos: ADMISIÓN 0,08–0,18 mm · ESCAPE 0,18–0,28 mm.',
      'Anota todas las medidas. Si alguna está fuera de rango, hay que desmontar los árboles de levas y cambiar las pastillas de reglaje (usa el tensor de cadena y las marcas de distribución).',
      'Pastilla nueva = pastilla actual + (holgura medida − holgura objetivo).',
      'Monta los árboles alineando las marcas, aprieta los soportes a 10 N·m en cruz, y verifica de nuevo las holguras.',
      'Monta la tapa de balancines con junta nueva (14 N·m) y el resto de componentes.',
    ],
    tips: 'Si nunca has calado una distribución, este trabajo es mejor dejarlo a un taller: un error puede dañar el motor. Las válvulas de escape tienden a CERRAR su holgura con el uso.',
  },
  {
    id: 'sincronizar',
    name: 'Sincronización de mariposas',
    category: 'motor',
    km: 12000,
    months: null,
    first: 1000,
    duration: '1 h 30 min',
    difficulty: 4,
    tools: [
      'Vacuómetro de 4 relojes o columnas',
      'Diagnóstico Suzuki (modo TPS/ajuste) opcional',
      'Destornillador plano fino (tornillos de ajuste de bypass)',
      'Ventilador (el motor se calienta sin ir en marcha)',
    ],
    parts: [],
    torques: [],
    steps: [
      'Calienta el motor a temperatura de funcionamiento.',
      'Levanta el depósito (usa un depósito auxiliar o alarga el manguito) y conecta el vacuómetro a las tomas de vacío de cada cuerpo de mariposa.',
      'Con el motor al ralentí (1.200–1.400 rpm), compara las lecturas de los 4 cilindros.',
      'Ajusta los tornillos de aire (bypass) de cada cuerpo hasta igualar el vacío.',
      'Da unos golpes de gas y verifica que las lecturas vuelven a coincidir.',
      'Ajusta el ralentí a 1.200–1.400 rpm, desconecta el vacuómetro y tapa las tomas.',
    ],
    tips: 'Síntoma de desincronización: ralentí irregular y tirones a bajas vueltas.',
  },
  {
    id: 'acelerador-embrague',
    name: 'Cables de gas y embrague',
    category: 'transmision',
    km: 6000,
    months: null,
    first: 1000,
    duration: '20 min',
    difficulty: 1,
    tools: ['Llaves fijas de 10 y 12 mm', 'Aceite de cables'],
    parts: [],
    torques: [],
    steps: [
      'Comprueba el juego libre del puño de gas: 2,0–4,0 mm. Ajusta con el tensor del cable junto al puño.',
      'Gira el manillar de tope a tope: el ralentí no debe subir. Si sube, el cable está demasiado tenso o mal guiado.',
      'Comprueba el juego libre de la maneta de embrague: 10–15 mm en el extremo de la maneta.',
      'Ajusta con la ruedecilla de la maneta o con el tensor del cable en el motor.',
      'Lubrica los cables y los pivotes de las manetas.',
    ],
    tips: '',
  },
  {
    id: 'neumaticos',
    name: 'Neumáticos: revisar',
    category: 'chasis',
    km: 6000,
    months: null,
    duration: '10 min',
    difficulty: 1,
    tools: ['Manómetro', 'Medidor de profundidad de dibujo'],
    parts: [],
    torques: [
      { part: 'Eje delantero', nm: 100 },
      { part: 'Tornillos de presión del eje delantero', nm: 23 },
      { part: 'Tuerca eje trasero', nm: 100 },
    ],
    steps: [
      'Mide la presión en frío: delantero 2,5 bar, trasero 2,9 bar.',
      'Mide la profundidad del dibujo: mínimo legal 1,6 mm (recomendado cambiar con 2 mm en el delantero).',
      'Revisa cortes, grietas, objetos clavados y la fecha de fabricación (DOT). Cambia neumáticos de más de 5 años.',
      'Si desmontas ruedas: eje delantero 100 N·m, tornillos de presión del eje 23 N·m, eje trasero 100 N·m.',
    ],
    tips: 'Revisa la presión cada 2 semanas: es la revisión más barata y la que más afecta a tu seguridad.',
  },
  {
    id: 'direccion-suspension',
    name: 'Dirección y suspensiones',
    category: 'chasis',
    km: 12000,
    months: null,
    first: 1000,
    duration: '30 min',
    difficulty: 2,
    tools: ['Caballetes delantero y trasero', 'Llave dinamométrica', 'Vasos 10–32 mm'],
    parts: [],
    torques: [
      { part: 'Tuerca pipa de dirección (tija superior)', nm: 90 },
      { part: 'Tornillos tija superior (horquilla)', nm: 23 },
      { part: 'Tornillos tija inferior (horquilla)', nm: 23 },
      { part: 'Tornillos semimanillares', nm: 23 },
      { part: 'Eje del basculante', nm: 100 },
      { part: 'Amortiguador trasero (superior e inferior)', nm: 50 },
    ],
    steps: [
      'Con la rueda delantera en el aire, gira el manillar de tope a tope: debe moverse suave, sin puntos duros.',
      'Sujeta las botellas de la horquilla abajo y empuja/tira adelante-atrás: no debe haber holgura en la pipa.',
      'Revisa las barras de horquilla: sin picaduras ni restos de aceite (retenes).',
      'Bombea la horquilla y el amortiguador trasero: deben amortiguar sin ruidos ni rebotes.',
      'Con la rueda trasera en el aire, mueve el basculante lateralmente: no debe tener holgura.',
      'Revisa los aprietes indicados si notas holguras.',
    ],
    tips: 'Si la pipa tiene holgura, el ajuste de rodamientos requiere un procedimiento específico: consulta el manual o un taller.',
  },
  {
    id: 'escape',
    name: 'Tornillería del escape',
    category: 'motor',
    km: 12000,
    months: null,
    first: 1000,
    duration: '15 min',
    difficulty: 1,
    tools: ['Vaso de 10 y 12 mm', 'Alargo', 'Llave dinamométrica'],
    parts: [],
    torques: [
      { part: 'Tuercas colector a culata', nm: 23 },
      { part: 'Tornillos conexión colector-silencioso', nm: 23 },
      { part: 'Tornillo soporte silencioso', nm: 23 },
    ],
    steps: [
      'Con el motor frío, comprueba el apriete de las tuercas del colector en la culata.',
      'Comprueba abrazaderas y tornillos de unión y soporte del silencioso.',
      'Busca marcas negras de hollín en las uniones: indican fugas.',
    ],
    tips: '',
  },
  {
    id: 'tornilleria',
    name: 'Tornillería del chasis',
    category: 'chasis',
    km: 6000,
    months: null,
    first: 1000,
    duration: '30 min',
    difficulty: 1,
    tools: ['Juego de vasos y llaves Allen métricas', 'Llave dinamométrica'],
    parts: [],
    torques: [
      { part: 'Eje delantero', nm: 100 },
      { part: 'Tornillos de presión eje delantero', nm: 23 },
      { part: 'Tuerca eje trasero', nm: 100 },
      { part: 'Tuerca pipa de dirección', nm: 90 },
      { part: 'Tornillos tijas (sup. e inf.)', nm: 23 },
      { part: 'Tornillos pinzas delanteras', nm: 35 },
      { part: 'Tornillos bomba de freno delantera', nm: 10 },
      { part: 'Eje del basculante', nm: 100 },
      { part: 'Tornillos estriberas', nm: 23 },
      { part: 'Tornillos subchasis', nm: 50 },
    ],
    steps: [
      'Recorre la moto verificando con la dinamométrica los aprietes de la tabla.',
      'No sueltes y vuelvas a apretar: sólo comprueba que el tornillo no gira al par indicado.',
      'Presta especial atención a ejes, tijas, pinzas y estriberas.',
    ],
    tips: '',
  },
  {
    id: 'pair',
    name: 'Sistema PAIR (aire secundario)',
    category: 'motor',
    km: 12000,
    months: null,
    duration: '20 min',
    difficulty: 2,
    tools: ['Destornillador', 'Vaso de 8 mm'],
    parts: [],
    torques: [
      { part: 'Tornillos tapa válvula de láminas PAIR', nm: 10 },
    ],
    steps: [
      'Levanta el depósito y localiza la válvula PAIR sobre la tapa de balancines.',
      'Revisa manguitos: sin grietas y bien conectados.',
      'Desmonta las tapas de las válvulas de láminas y comprueba que las láminas no tienen carbonilla ni están deformadas.',
      'Limpia y monta (10 N·m).',
    ],
    tips: '',
  },
  {
    id: 'bateria',
    name: 'Batería: revisar',
    category: 'electrico',
    km: null,
    months: 6,
    duration: '10 min',
    difficulty: 1,
    tools: ['Polímetro', 'Destornillador de estrella / llave de 10 mm', 'Cepillo de alambre'],
    parts: [],
    torques: [
      { part: 'Terminales de batería', nm: 5, note: 'apriete firme sin forzar' },
    ],
    steps: [
      'Quita el asiento del piloto para acceder a la batería.',
      'Mide la tensión con la moto apagada: 12,6 V o más = cargada; menos de 12,4 V = cárgala.',
      'Con el motor a 5.000 rpm debe marcar entre 13,5 y 15 V (regulador/estátor correctos).',
      'Limpia y protege los bornes si hay sulfato.',
    ],
    tips: 'Si no usas la moto en invierno, conéctala a un mantenedor de carga.',
  },
];

const TASK_MAP = Object.fromEntries(TASKS.map((t) => [t.id, t]));
