// Datos técnicos de la Suzuki DR-Z400S / DR-Z400SM (2006, K6).
// Plan de mantenimiento, capacidades y pares del manual de servicio Suzuki DR-Z400S/SM (2000-2009).
// Donde la S (trail) y la SM (supermotard) difieren se indican ambos valores.
// Verifica siempre los valores críticos con el manual de taller de tu unidad.

BIKES.push({
  id: 'drz400',
  brand: 'suzuki',
  short: 'DR-Z 400',
  name: 'Suzuki DR-Z 400 S/SM',
  years: '2006',
  unit: 'km',
  before: 500,
  source: 'el manual de servicio de Suzuki DR-Z400S/SM (modelos 2000–2009, incluye K6)',
  specs: [
    { label: 'Motor', value: 'Monocilíndrico 4T 398 cc, DOHC 4 válvulas, refrigeración líquida, cárter seco (aceite en el chasis)' },
    { label: 'Aceite motor', value: 'SAE 10W-40, API SF o SG' },
    { label: 'Capacidad aceite', value: '1,7 L (cambio) · 1,8 L (con filtro) · 1,9 L (en seco)' },
    { label: 'Bujía', value: 'NGK CR8E o DENSO U24ESR-N · distancia 0,7–0,8 mm' },
    { label: 'Holgura válvulas (en frío)', value: 'Admisión 0,10–0,20 mm · Escape 0,20–0,30 mm' },
    { label: 'Refrigerante', value: '1,25 L' },
    { label: 'Líquido de frenos', value: 'DOT 4' },
    { label: 'Ralentí', value: '1.500 ± 100 rpm' },
    { label: 'Filtro de aire', value: 'Espuma de poliuretano (se lava y se aceita con SAE 30 o 10W-40)' },
    { label: 'Cadena', value: 'RK520KZO · 112 eslabones' },
    { label: 'Holgura cadena', value: '40–50 mm en el centro entre piñón y corona' },
    { label: 'Neumáticos S', value: '80/100-21 · 120/90-18' },
    { label: 'Neumáticos SM', value: '120/70R17 · 140/70R17' },
    { label: 'Presión S (en frío)', value: 'Solo 1,25 / 1,50 bar · Con pasajero 1,25 / 1,75 bar' },
    { label: 'Presión SM (en frío)', value: 'Solo 1,75 / 2,00 bar · Con pasajero 1,75 / 2,25 bar' },
    { label: 'Batería', value: '12 V 6,5 Ah' },
    { label: 'Depósito', value: '10 L (reserva 2,3 L)' },
  ],
  tasks: [
    {
      id: 'aceite',
      name: 'Cambio de aceite motor',
      category: 'motor',
      every: 6000,
      months: 6,
      first: 1000,
      duration: '30 min',
      difficulty: 1,
      tools: [
        'Llaves para los 2 tapones de vaciado (cárter y chasis)',
        'Llave dinamométrica (rango 10–30 N·m)',
        'Bandeja de vaciado (mín. 2 L)',
        'Embudo, guantes y trapos',
      ],
      parts: ['1,7 L de aceite SAE 10W-40 API SF/SG (1,8 L si cambias filtro)', 'Arandelas de los tapones de vaciado'],
      torques: [
        { part: 'Tapón de vaciado del cárter', nm: 21 },
        { part: 'Tapón de vaciado del chasis (depósito de aceite)', nm: 18, note: 'la conicidad de la arandela mira hacia el tapón' },
      ],
      steps: [
        'Calienta el motor unos minutos: el aceite sale mejor en caliente.',
        'Pon la bandeja y quita los dos tapones de vaciado (el del cárter y el del chasis, que hace de depósito de aceite) y el tapón de llenado.',
        'Deja escurrir todo el aceite.',
        'Monta los tapones con arandelas nuevas: cárter a 21 N·m y chasis a 18 N·m. En el del chasis, la parte cónica de la arandela va hacia el tapón.',
        'Echa el aceite nuevo (1,7 L; 1,8 L si has cambiado filtro) y pon el tapón de llenado.',
        'Con la moto recta en suelo llano, arranca y deja el motor 3 minutos al ralentí.',
        'Para el motor, espera 3 minutos y mira la varilla: el nivel debe estar entre L y F. Completa si hace falta.',
      ],
      tips: 'Es un motor de cárter seco: el nivel se mira siempre con el motor recién parado tras 3 minutos al ralentí, no en frío. En caliente el nivel sube.',
    },
    {
      id: 'filtro-aceite',
      name: 'Cambio filtro de aceite',
      category: 'motor',
      every: 18000,
      months: 18,
      first: 1000,
      duration: '15 min (junto con el aceite)',
      difficulty: 1,
      tools: ['Llaves para los tornillos de la tapa del filtro', 'Trapos'],
      parts: ['Filtro de aceite', 'Junta tórica de la tapa del filtro'],
      torques: [],
      steps: [
        'Hazlo con el aceite ya vaciado.',
        'Quita la tapa del filtro y saca el filtro.',
        'Coloca el filtro nuevo.',
        'Comprueba que el muelle y la junta tórica nueva de la tapa están bien colocados, y que la junta tórica de detrás del filtro está en su sitio.',
        'Monta la tapa y aprieta sus tuercas con firmeza.',
        'Rellena 1,8 L de aceite y comprueba el nivel y las fugas.',
      ],
      tips: 'El filtro es muy barato: muchos propietarios lo cambian en cada cambio de aceite.',
    },
    {
      id: 'filtro-aire-limpiar',
      name: 'Filtro de aire: limpiar y aceitar',
      category: 'motor',
      every: 6000,
      months: 6,
      duration: '30 min (+ secado)',
      difficulty: 1,
      tools: ['Recipiente para lavar', 'Guantes', 'Trapo limpio'],
      parts: ['Disolvente no inflamable para limpiar', 'Aceite de motor SAE 30 o 10W-40 (o aceite de filtros)'],
      torques: [],
      steps: [
        'Quita la tapa lateral izquierda y saca el filtro de aire.',
        'Separa la espuma de su soporte.',
        'Lávala en disolvente no inflamable y apriétala entre las palmas para secarla. No la retuerzas.',
        'Empápala en aceite de motor SAE 30 o 10W-40 y escurre el sobrante apretando.',
        'Revisa que no esté rota: si tiene cortes, cámbiala.',
        'Móntala bien asentada en la caja para que no pase polvo por los bordes.',
      ],
      tips: 'Si ruedas por campo con polvo, límpialo mucho más a menudo que cada 6.000 km.',
    },
    {
      id: 'filtro-aire-cambiar',
      name: 'Filtro de aire: sustituir',
      category: 'motor',
      every: 18000,
      months: 18,
      resets: ['filtro-aire-limpiar'],
      duration: '20 min',
      difficulty: 1,
      tools: ['Destornillador'],
      parts: ['Filtro de aire de espuma', 'Aceite para el filtro'],
      torques: [],
      steps: [
        'Quita la tapa lateral izquierda y saca el filtro usado.',
        'Limpia la caja del filtro.',
        'Aceita el filtro nuevo y escurre el sobrante.',
        'Móntalo bien asentado y cierra la tapa.',
      ],
      tips: 'Nunca arranques la moto sin el filtro puesto.',
    },
    {
      id: 'bujia-revisar',
      name: 'Bujía: revisar',
      category: 'electrico',
      every: 6000,
      months: 6,
      duration: '15 min',
      difficulty: 1,
      tools: ['Llave de bujías', 'Galgas de espesores', 'Llave dinamométrica'],
      parts: [],
      torques: [
        { part: 'Bujía', nm: 11 },
      ],
      steps: [
        'Con el motor frío, quita la pipa y saca la bujía.',
        'Quita la carbonilla si la hay.',
        'Ajusta la distancia entre electrodos a 0,7–0,8 mm.',
        'Enrosca a mano y aprieta a 11 N·m.',
      ],
      tips: 'Una bujía blanca indica mezcla pobre; negra y húmeda, mezcla rica o bujía demasiado fría.',
    },
    {
      id: 'bujia-cambiar',
      name: 'Bujía: sustituir',
      category: 'electrico',
      every: 12000,
      months: 12,
      resets: ['bujia-revisar'],
      duration: '15 min',
      difficulty: 1,
      tools: ['Llave de bujías', 'Galgas de espesores', 'Llave dinamométrica'],
      parts: ['Bujía NGK CR8E o DENSO U24ESR-N'],
      torques: [
        { part: 'Bujía', nm: 11 },
      ],
      steps: [
        'Con el motor frío, sopla alrededor de la bujía y sácala.',
        'Comprueba la distancia entre electrodos de la nueva: 0,7–0,8 mm.',
        'Enrosca a mano hasta el tope y aprieta a 11 N·m.',
        'Monta la pipa hasta que encaje.',
      ],
      tips: 'Suzuki también admite CR9E (más fría) o CR7E (más caliente) según el uso.',
    },
    {
      id: 'valvulas',
      name: 'Holgura de válvulas',
      category: 'motor',
      every: 24000,
      months: 24,
      duration: '2–3 h',
      difficulty: 4,
      tools: ['Galgas de espesores', 'Juego de llaves y vasos métricos', 'Llave dinamométrica'],
      parts: ['Junta de la tapa de balancines (si está dañada)', 'Pastillas de reglaje de la medida necesaria'],
      torques: [
        { part: 'Tornillos tapa de culata', nm: 14, note: 'primero todos a 10 N·m y luego a 14 N·m' },
        { part: 'Bujía', nm: 11 },
      ],
      steps: [
        'Con el motor frío, desmonta asiento, depósito y tapa de culata.',
        'Pon el pistón en el punto muerto superior de compresión.',
        'Mide la holgura de cada válvula: admisión 0,10–0,20 mm, escape 0,20–0,30 mm.',
        'Si alguna está fuera de rango, se ajusta cambiando la pastilla de reglaje (taqué).',
        'Tras ajustar, gira el cigüeñal unas vueltas y vuelve a medir.',
        'Monta la tapa de culata: tornillos primero a 10 N·m y luego a 14 N·m.',
      ],
      tips: 'Anota las medidas cada vez: si una válvula va cerrando holgura con el tiempo, es señal de desgaste.',
    },
    {
      id: 'carburador',
      name: 'Carburador: ralentí y cable del gas',
      category: 'motor',
      every: 6000,
      months: 6,
      first: 1000,
      duration: '15 min',
      difficulty: 1,
      tools: ['Destornillador', 'Llaves para el tensor del cable del gas'],
      parts: [],
      torques: [],
      steps: [
        'Con el motor caliente, ajusta el ralentí a 1.500 ± 100 rpm.',
        'Comprueba el juego del puño del gas y ajústalo con el tensor del cable.',
        'Gira el manillar de tope a tope con el motor al ralentí: las revoluciones no deben subir.',
      ],
      tips: 'Si la moto va a estar parada mucho tiempo, vacía la cuba del carburador.',
    },
    {
      id: 'embrague',
      name: 'Embrague: juego de la maneta',
      category: 'transmision',
      every: 6000,
      months: 6,
      duration: '10 min',
      difficulty: 1,
      tools: ['Llaves para el tensor del cable del embrague'],
      parts: [],
      torques: [],
      steps: [
        'Comprueba el juego libre de la maneta del embrague.',
        'Ajústalo con el tensor del cable si hace falta.',
        'Lubrica el cable si va duro.',
      ],
      tips: 'Un embrague sin juego acaba patinando y quemando discos.',
    },
    {
      id: 'cadena-engrasar',
      name: 'Cadena: engrasar',
      category: 'transmision',
      every: 1000,
      months: null,
      duration: '15 min',
      difficulty: 1,
      tools: ['Caballete', 'Limpiador de cadenas y cepillo', 'Spray de cadena', 'Trapos'],
      parts: ['Spray de cadena'],
      torques: [],
      steps: [
        'Levanta la rueda trasera y pon punto muerto.',
        'Limpia la cadena con limpiador compatible con juntas tóricas y deja secar.',
        'Engrasa la cara interior mientras giras la rueda.',
        'Retira el sobrante para que no llegue al neumático ni al disco.',
      ],
      tips: 'Suzuki indica engrasarla cada 1.000 km; tras barro o lluvia, límpiala y engrásala antes.',
    },
    {
      id: 'cadena-tensar',
      name: 'Cadena: holgura y desgaste',
      category: 'transmision',
      every: 6000,
      months: 6,
      first: 1000,
      duration: '30 min',
      difficulty: 2,
      tools: [
        'Caballete',
        'Llave para la tuerca del eje trasero',
        'Llaves para las contratuercas y tensores',
        'Llave dinamométrica (hasta 120 N·m)',
        'Regla o metro',
      ],
      parts: [],
      torques: [
        { part: 'Tuerca del eje trasero', nm: 110, note: 'versión europea (100 N·m en otros mercados)' },
        { part: 'Tuercas de la corona', nm: 30 },
        { part: 'Tornillos de los rodillos de cadena', nm: 40 },
      ],
      steps: [
        'Mide la holgura en el centro del tramo entre piñón y corona: 40–50 mm.',
        'Para ajustar: afloja la tuerca del eje trasero y las contratuercas de los tensores.',
        'Gira los tensores hasta la holgura correcta. Las marcas de los dos lados del basculante deben quedar iguales para que la rueda vaya alineada.',
        'Aprieta las contratuercas y la tuerca del eje a 110 N·m.',
        'Revisa piñón, corona, rodillos y patín: si están gastados, cambia el kit completo.',
      ],
      tips: 'La cadena de serie es RK520KZO de 112 eslabones.',
    },
    {
      id: 'frenos-revisar',
      name: 'Frenos: pastillas, discos y latiguillos',
      category: 'frenos',
      every: 6000,
      months: 6,
      first: 1000,
      duration: '20 min',
      difficulty: 1,
      tools: ['Linterna', 'Calibre', 'Llave dinamométrica (si hay que desmontar)'],
      parts: ['Pastillas de freno (si están gastadas)'],
      torques: [
        { part: 'Tornillos pinza de freno delantera', nm: 26 },
        { part: 'Pasadores de las pastillas (del. y tras.)', nm: 18 },
        { part: 'Tornillos de los discos (del. y tras.)', nm: 10 },
        { part: 'Tornillos banjo de los latiguillos', nm: 23 },
        { part: 'Purgadores de freno', nm: 7.5, note: 'SM: 6 N·m' },
        { part: 'Tornillo del pedal de freno', nm: 29 },
      ],
      steps: [
        'Revisa el grosor de las pastillas; cámbialas si están cerca de la marca de desgaste.',
        'Revisa los discos: sin grietas ni rayas profundas.',
        'Comprueba que los latiguillos no tengan grietas ni fugas.',
        'Mira el nivel de líquido de freno delantero y trasero.',
      ],
      tips: 'Suzuki pide cambiar los latiguillos de freno cada 4 años aunque parezcan bien.',
    },
    {
      id: 'liquido-frenos',
      name: 'Líquido de frenos',
      category: 'frenos',
      every: null,
      months: 24,
      duration: '45 min',
      difficulty: 2,
      tools: ['Llave para los purgadores', 'Tubo transparente y botella', 'Trapos'],
      parts: ['Líquido de frenos DOT 4'],
      torques: [
        { part: 'Purgadores de freno', nm: 7.5, note: 'SM: 6 N·m' },
        { part: 'Tornillos banjo de los latiguillos', nm: 23 },
      ],
      steps: [
        'Protege la pintura y los plásticos del líquido de frenos.',
        'Retira el líquido viejo del depósito y rellena con DOT 4 nuevo.',
        'Purga cada pinza hasta que salga líquido limpio sin burbujas, sin dejar que se vacíe el depósito.',
        'Ajusta el nivel, cierra el depósito y comprueba el tacto antes de rodar.',
      ],
      tips: 'Usa sólo DOT 4 y no lo mezcles con otros tipos.',
    },
    {
      id: 'latiguillos',
      name: 'Latiguillos de freno y tubos de gasolina',
      category: 'frenos',
      every: null,
      months: 48,
      duration: '1,5 h',
      difficulty: 3,
      tools: ['Llaves', 'Llave dinamométrica', 'Material para purgar frenos'],
      parts: ['Latiguillos de freno', 'Arandelas de cobre nuevas', 'Tubo de gasolina', 'Líquido DOT 4'],
      torques: [
        { part: 'Tornillos banjo de los latiguillos', nm: 23 },
      ],
      steps: [
        'Sustituye los latiguillos de freno delantero y trasero con arandelas nuevas; aprieta los banjos a 23 N·m.',
        'Rellena y purga los frenos.',
        'Sustituye el tubo de gasolina y comprueba que no haya fugas.',
      ],
      tips: 'Suzuki pide cambiar ambos cada 4 años: la goma se agrieta por dentro aunque por fuera parezca bien.',
    },
    {
      id: 'refrigerante',
      name: 'Refrigerante: sustituir',
      category: 'refrigeracion',
      every: null,
      months: 24,
      duration: '45 min',
      difficulty: 2,
      tools: ['Bandeja', 'Embudo'],
      parts: ['1,25 L de refrigerante'],
      torques: [],
      steps: [
        'Con el motor frío, vacía el circuito y recoge el refrigerante (es tóxico).',
        'Rellena con 1,25 L de refrigerante nuevo y purga el aire.',
        'Arranca, deja que se caliente y vuelve a comprobar el nivel en frío.',
      ],
      tips: 'Nunca abras el tapón del radiador con el motor caliente.',
    },
    {
      id: 'manguitos',
      name: 'Manguitos de radiador y de aceite',
      category: 'refrigeracion',
      every: 6000,
      months: 6,
      duration: '10 min',
      difficulty: 1,
      tools: ['Linterna'],
      parts: [],
      torques: [],
      steps: [
        'Revisa los manguitos del radiador y los de aceite: sin grietas, fugas ni abrazaderas flojas.',
        'Revisa el tubo de gasolina.',
      ],
      tips: 'Cambia cualquier manguito que esté duro o agrietado.',
    },
    {
      id: 'escape',
      name: 'Escape: apriete',
      category: 'motor',
      every: 12000,
      months: 12,
      first: 1000,
      duration: '10 min',
      difficulty: 1,
      tools: ['Llaves y vasos métricos', 'Llave dinamométrica'],
      parts: [],
      torques: [
        { part: 'Tuercas y tornillo del colector de escape', nm: 23 },
        { part: 'Tornillo de unión del silenciador', nm: 20 },
        { part: 'Tornillos y tuerca de sujeción del silenciador', nm: 23 },
      ],
      steps: [
        'Con el escape frío, aprieta las tuercas del colector a 23 N·m.',
        'Aprieta el tornillo de unión del silenciador a 20 N·m y los de sujeción a 23 N·m.',
      ],
      tips: 'Una fuga en el colector hace petardeos al cortar gas.',
    },
    {
      id: 'neumaticos-radios',
      name: 'Neumáticos y radios',
      category: 'chasis',
      every: 6000,
      months: 6,
      first: 1000,
      duration: '20 min',
      difficulty: 1,
      tools: ['Manómetro', 'Llave de radios', 'Llave dinamométrica'],
      parts: [],
      torques: [
        { part: 'Radios', nm: 3 },
        { part: 'Tuerca del eje delantero', nm: 42, note: 'SM: 39 N·m' },
        { part: 'Tornillos de apriete del eje delantero', nm: 18 },
        { part: 'Tuerca del eje trasero', nm: 110, note: 'versión europea' },
      ],
      steps: [
        'Mide la presión en frío. S: 1,25 bar delante y 1,50 detrás (1,75 detrás con pasajero). SM: 1,75 delante y 2,00 detrás (2,25 con pasajero).',
        'Revisa el dibujo y busca cortes o deformaciones.',
        'Comprueba que los radios están firmes y apriétalos a 3 N·m si hace falta.',
      ],
      tips: 'Los radios se revisan por primera vez a los 1.000 km: se aflojan al principio.',
    },
    {
      id: 'direccion',
      name: 'Dirección',
      category: 'chasis',
      every: 12000,
      months: 12,
      first: 1000,
      duration: '30 min',
      difficulty: 2,
      tools: ['Caballete', 'Llave dinamométrica'],
      parts: [],
      torques: [
        { part: 'Tuerca superior de la pipa de dirección', nm: 90 },
        { part: 'Tornillos tija superior', nm: 30, note: 'SM: 23 N·m' },
        { part: 'Tornillos tija inferior', nm: 32, note: 'SM: 23 N·m' },
        { part: 'Tornillos abrazadera del manillar', nm: 23 },
      ],
      steps: [
        'Con la rueda delantera en el aire, comprueba que la dirección gira suave de tope a tope.',
        'Mueve la horquilla adelante y atrás: no debe haber holgura en la pipa.',
        'Si hay holgura o puntos duros, ajusta o cambia los rodamientos.',
      ],
      tips: 'Los rodamientos de dirección sufren mucho con el lavado a presión: no apuntes a la pipa.',
    },
    {
      id: 'suspensiones',
      name: 'Horquilla y suspensión trasera',
      category: 'chasis',
      every: 12000,
      months: 12,
      duration: '30 min',
      difficulty: 2,
      tools: ['Caballete', 'Llave dinamométrica', 'Grasa'],
      parts: [],
      torques: [
        { part: 'Tuercas del amortiguador (superior e inferior)', nm: 55 },
        { part: 'Tuercas de bieletas y biela del amortiguador', nm: 100 },
        { part: 'Tuerca eje del basculante', nm: 77, note: 'valor de la DR-Z400S' },
      ],
      steps: [
        'Revisa que la horquilla no pierda aceite y que las barras no tengan marcas.',
        'Comprueba el amortiguador: sin fugas y con un funcionamiento suave.',
        'Revisa holguras de basculante y bieletas y engrásalas si hace falta.',
      ],
      tips: 'Si la horquilla pierde aceite, limpia los retenes con una herramienta de limpieza antes de cambiarlos: a menudo es sólo suciedad.',
    },
    {
      id: 'tornilleria',
      name: 'Tornillería del chasis',
      category: 'chasis',
      every: 6000,
      months: 6,
      first: 1000,
      duration: '30 min',
      difficulty: 1,
      tools: ['Juego de llaves y vasos métricos', 'Llave dinamométrica'],
      parts: [],
      torques: [
        { part: 'Tuercas y tornillos del subchasis', nm: 35 },
        { part: 'Tornillo del caballete lateral', nm: 50 },
        { part: 'Tuerca del caballete lateral', nm: 55 },
        { part: 'Tornillos de las bombas de freno', nm: 10 },
      ],
      steps: [
        'Revisa el apriete de toda la tornillería del chasis: tijas, ejes, basculante, amortiguador, subchasis, caballete y frenos.',
        'Aprieta con la dinamométrica a los pares indicados.',
      ],
      tips: 'Un monocilíndrico vibra mucho: esta revisión es más importante que en una moto de varios cilindros.',
    },
    {
      id: 'pair',
      name: 'Sistema PAIR (aire secundario)',
      category: 'motor',
      every: 12000,
      months: 12,
      duration: '15 min',
      difficulty: 1,
      tools: ['Destornillador'],
      parts: [],
      torques: [],
      steps: [
        'Revisa los manguitos del sistema PAIR: sin grietas ni conexiones sueltas.',
        'Comprueba la válvula de láminas del sistema.',
      ],
      tips: 'Lo montan las versiones europeas.',
    },
  ],
});
