// Datos técnicos de la KTM 250 EXC 2T (2009).
// Plan de mantenimiento (uso de ocio "H"), capacidades y pares del manual de usuario oficial 2009
// 125-300 EXC/XC (art. 3211353en). Los intervalos van en horas de motor (contador "H" del cuadro).
// Verifica siempre los valores críticos con el manual de taller de tu unidad.

BIKES.push({
  id: 'exc250',
  brand: 'ktm',
  short: 'EXC 250',
  name: 'KTM 250 EXC 2T',
  years: '2009',
  unit: 'h',
  before: 2,
  source: 'el manual de usuario oficial de la KTM 250 EXC 2009 (plan para uso de ocio)',
  specs: [
    { label: 'Motor', value: '2T monocilíndrico 249 cc, refrigeración líquida, válvula de escape TVC' },
    { label: 'Carburador', value: 'Keihin PWK 36S AG' },
    { label: 'Mezcla', value: '1:60 con aceite 2T de alta calidad (Motorex Cross Power 2T) · en caso de duda 1:40' },
    { label: 'Gasolina', value: 'Sin plomo 95 octanos mínimo' },
    { label: 'Aceite caja de cambios', value: '0,7 L · 15W-50 (Motorex Top Speed 4T)' },
    { label: 'Bujía', value: 'NGK BR7ES · distancia 0,6 mm' },
    { label: 'Refrigerante', value: '1,2 L · 50 % anticongelante (mín. -25 °C)' },
    { label: 'Nivel refrigerante', value: '10 mm por encima de las aletas del radiador, en frío' },
    { label: 'Líquido frenos y embrague', value: 'DOT 5.1 (nunca DOT 5, que es de silicona)' },
    { label: 'Cadena', value: '5/8 x 1/4" (520)' },
    { label: 'Tensión cadena', value: '8–10 mm entre cadena y basculante al final del patín (rueda trasera en el aire)' },
    { label: 'Desgaste cadena', value: 'Máx. 272 mm en 18 rodillos (tirando con 10–15 kg)' },
    { label: 'Neumáticos', value: '90/90-21 · 140/80-18' },
    { label: 'Presión neumáticos', value: 'Campo 1,0 bar · Carretera (solo) 1,5 del. / 2,0 tras.' },
    { label: 'Frenos: límites', value: 'Pastillas mín. 1 mm · Disco del. mín. 2,5 mm · Disco tras. mín. 3,5 mm' },
    { label: 'Horquilla WP 4860 MXMA PA', value: 'Compresión 22 clics · Rebote 22 clics · Precarga 2 vueltas · Aceite SAE 5' },
    { label: 'Amortiguador WP 5018 PDS DCC', value: 'Compresión baja 15 clics · alta 1,5 vueltas · Rebote 24 clics · Precarga muelle 9 mm' },
    { label: 'Sag (hundimiento)', value: 'Estático 35 ± 2 mm · En marcha 105 ± 5 mm' },
    { label: 'Batería (arranque eléctrico)', value: '12 V 3 Ah' },
  ],
  tasks: [
    {
      id: 'filtro-aire',
      name: 'Filtro de aire: limpiar y aceitar',
      category: 'motor',
      every: 5,
      months: null,
      duration: '30 min (+ secado)',
      difficulty: 1,
      tools: ['Cubo o recipiente para lavar', 'Guantes', 'Trapo limpio'],
      parts: ['Limpiador de filtros de espuma (Motorex Twin Air Dirt Bio Remover)', 'Aceite de filtro (Motorex Twin Air Liquid Bio Power)', 'Filtro de repuesto (recomendable tener dos)'],
      torques: [],
      steps: [
        'Levanta la tapa de la caja del filtro y tira de ella hacia delante.',
        'Suelta la parte inferior de la sujeción del filtro, apártala y saca el filtro con su soporte.',
        'Tapa la boca de admisión con un trapo limpio para que no entre suciedad.',
        'Lava el filtro en el limpiador especial. NUNCA con gasolina ni disolventes: estropean la espuma.',
        'Escúrrelo apretando, sin retorcerlo, y déjalo secar del todo.',
        'Aceítalo con aceite de filtro de calidad, repartido por toda la espuma.',
        'Limpia la caja del filtro y revisa que el manguito del carburador no esté dañado.',
        'Coloca el filtro en su soporte, céntralo en la caja y sujétalo con la pinza. Nunca arranques sin filtro.',
      ],
      tips: 'KTM pide limpiarlo antes de cada carrera o siempre que haya acumulado polvo. Con barro o polvo, límpialo después de cada salida.',
    },
    {
      id: 'cadena',
      name: 'Cadena: limpiar, engrasar y tensar',
      category: 'transmision',
      every: 5,
      months: null,
      duration: '20 min',
      difficulty: 1,
      tools: [
        'Caballete o soporte para levantar la moto',
        'Llave para la tuerca del eje trasero (M20x1,5)',
        'Llaves para contratuercas y tornillos tensores',
        'Llave dinamométrica (hasta 80 N·m)',
        'Limpiador de cadenas (Motorex Chain Clean) y spray para X-ring (Motorex Chainlube)',
      ],
      parts: ['Limpiador y spray de cadena'],
      torques: [
        { part: 'Tuerca del eje trasero (M20x1,5)', nm: 80 },
        { part: 'Tuercas de la corona (M8)', nm: 35, note: 'Loctite 243, en cruz' },
      ],
      steps: [
        'Quita el barro con agua abundante y la grasa vieja con limpiador de cadenas. Deja secar.',
        'Engrasa con spray para cadenas X-ring. Sin que llegue grasa al neumático ni al disco.',
        'Levanta la moto por el chasis para que la rueda trasera quede en el aire.',
        'Empuja la cadena hacia arriba al final del patín: entre cadena y basculante debe haber 8–10 mm, con el tramo superior tenso.',
        'Para ajustar: afloja la tuerca del eje, afloja las contratuercas y gira por igual los tornillos tensores de ambos lados.',
        'Comprueba que los tensores apoyan en los tornillos y que la rueda trasera está alineada con la delantera.',
        'Aprieta las contratuercas y la tuerca del eje a 80 N·m.',
        'Desgaste: tirando del tramo superior con 10–15 kg, 18 rodillos del tramo inferior no deben medir más de 272 mm. Revisa piñón, corona y guías.',
      ],
      tips: 'Si cambias la cadena, cambia también piñón y corona. El lado cerrado del clip del eslabón de cierre debe apuntar en el sentido de giro.',
    },
    {
      id: 'aceite-caja',
      name: 'Aceite de la caja de cambios',
      category: 'motor',
      every: 40,
      months: 12,
      first: 10,
      duration: '20 min',
      difficulty: 1,
      tools: [
        'Llave para el tapón de vaciado (M12x1,5, con imán)',
        'Llave dinamométrica de rango bajo',
        'Bandeja de vaciado',
        'Embudo o botella dosificadora (0,7 L)',
      ],
      parts: ['0,7 L de aceite 15W-50 (Motorex Top Speed 4T)', 'Junta del tapón de vaciado'],
      torques: [
        { part: 'Tapón de vaciado caja de cambios (M12x1,5)', nm: 20 },
      ],
      steps: [
        'Calienta el motor y pon la moto recta en suelo horizontal.',
        'Quita el tapón de vaciado y deja caer el aceite en la bandeja.',
        'Limpia el imán del tapón y revisa si hay restos metálicos.',
        'Monta el tapón con su junta y apriétalo a 20 N·m.',
        'Echa 0,7 L de aceite 15W-50 por el tapón de llenado de la tapa del embrague y ciérralo.',
        'Comprueba el nivel: con la moto vertical, al quitar el tornillo de control de la tapa del embrague debe asomar justo un poco de aceite.',
        'Arranca y revisa que no haya fugas.',
      ],
      tips: 'Cada 20 h comprueba el nivel. El aceite de caja es barato y el embrague lo agradece: muchos lo cambian cada 15–20 h.',
    },
    {
      id: 'bujia-revisar',
      name: 'Bujía: revisar',
      category: 'electrico',
      every: 20,
      months: null,
      first: 10,
      duration: '10 min',
      difficulty: 1,
      tools: ['Llave de bujías de 13/16" (20,8 mm)', 'Galgas de espesores', 'Cepillo de alambre suave', 'Llave dinamométrica'],
      parts: [],
      torques: [
        { part: 'Bujía (M14x1,25)', nm: 25 },
      ],
      steps: [
        'Limpia la zona alrededor de la bujía antes de sacarla.',
        'Desmonta la pipa y saca la bujía con el motor frío.',
        'Mira el color: marrón claro es correcto; negra y húmeda indica mezcla rica o bujía fría; blanca indica mezcla pobre.',
        'Ajusta la distancia entre electrodos a 0,6 mm.',
        'Limpia la pipa y comprueba que encaja firme.',
        'Enrosca a mano y aprieta a 25 N·m.',
      ],
      tips: 'Lleva siempre una bujía de repuesto: un 2T puede ensuciarla en una salida.',
    },
    {
      id: 'bujia-cambiar',
      name: 'Bujía: sustituir',
      category: 'electrico',
      every: 40,
      months: null,
      resets: ['bujia-revisar'],
      duration: '10 min',
      difficulty: 1,
      tools: ['Llave de bujías de 13/16" (20,8 mm)', 'Galgas de espesores', 'Llave dinamométrica'],
      parts: ['Bujía NGK BR7ES'],
      torques: [
        { part: 'Bujía (M14x1,25)', nm: 25 },
      ],
      steps: [
        'Con el motor frío, limpia alrededor de la bujía y sácala.',
        'Comprueba la distancia entre electrodos de la nueva: 0,6 mm.',
        'Enrosca a mano hasta el tope para no cruzar la rosca.',
        'Aprieta a 25 N·m y monta la pipa hasta que encaje.',
      ],
      tips: 'Aprovecha para limpiar la pipa y revisar que el cable de la bobina no esté dañado.',
    },
    {
      id: 'valvula-escape',
      name: 'Válvula de escape (TVC): revisar',
      category: 'motor',
      every: 20,
      months: null,
      duration: '1 h',
      difficulty: 3,
      tools: ['Llaves Allen y vasos métricos', 'Llave dinamométrica de rango bajo', 'Loctite 243', 'Limpiador de carbonilla'],
      parts: ['Juntas de las tapas de la válvula de escape (si están dañadas)'],
      torques: [
        { part: 'Válvula de escape: soporte (M5)', nm: 7, note: 'Loctite 243' },
        { part: 'Válvula de escape: trampilla de control (M6)', nm: 10, note: 'Loctite 243' },
        { part: 'Válvula de escape: palanca del segmento (M5)', nm: 6, note: 'Loctite 243' },
      ],
      steps: [
        'Desmonta las tapas de la válvula de escape del cilindro.',
        'Comprueba que las piezas de la válvula se mueven libres, sin agarrotarse por carbonilla.',
        'Limpia la carbonilla de las piezas.',
        'Monta con Loctite 243 y aprieta cada tornillo a su par.',
        'Comprueba con el motor en marcha que la válvula actúa: empieza a abrir a 5.500 rpm y abre del todo a 7.300–8.300 rpm según el muelle.',
      ],
      tips: 'Una válvula de escape agarrotada hace que el motor pierda fuerza arriba o abajo. Si no te ves seguro, llévala al taller.',
    },
    {
      id: 'piston-cilindro',
      name: 'Pistón, cilindro y láminas',
      category: 'motor',
      every: 40,
      months: null,
      duration: '3 h',
      difficulty: 4,
      tools: [
        'Juego de vasos y llaves métricas',
        'Llave dinamométrica',
        'Galgas de espesores y calibre',
        'Rasqueta de plástico para juntas',
      ],
      parts: ['Juntas de culata y de base del cilindro', 'Pistón y segmentos (si están fuera de medida)', 'Láminas de admisión (si están dañadas)'],
      torques: [
        { part: 'Tornillos de culata (M8)', nm: 27 },
        { part: 'Tuercas base del cilindro (M10)', nm: 35 },
        { part: 'Bujía (M14x1,25)', nm: 25 },
      ],
      steps: [
        'Vacía el refrigerante y desmonta escape, carburador, culata y cilindro según el manual.',
        'Revisa el desgaste del cilindro y del pistón (rayas, gripajes) y la holgura de los segmentos.',
        'Comprueba el rodamiento del bulón.',
        'Revisa la válvula de láminas de admisión: las láminas deben cerrar bien, sin grietas ni deformaciones.',
        'Monta con juntas nuevas. Aprieta las tuercas de la base del cilindro a 35 N·m y los tornillos de culata a 27 N·m, en cruz.',
        'Rellena el refrigerante, purga el circuito y haz un rodaje suave si has cambiado pistón o segmentos.',
      ],
      tips: 'El manual marca revisarlo cada 40 h en uso de ocio. En uso intenso o competición, cada 20 h.',
    },
    {
      id: 'embrague',
      name: 'Embrague: discos y muelles',
      category: 'transmision',
      every: 40,
      months: null,
      duration: '1,5 h',
      difficulty: 3,
      tools: ['Vasos y llaves métricas', 'Llave dinamométrica de rango bajo', 'Calibre (longitud de muelles y grosor de discos)'],
      parts: ['Junta de la tapa del embrague', 'Discos y muelles de embrague (si están fuera de medida)', '0,7 L de aceite 15W-50'],
      torques: [
        { part: 'Tornillos de tapas del motor (M5)', nm: 6 },
        { part: 'Tapón de vaciado caja de cambios (M12x1,5)', nm: 20 },
      ],
      steps: [
        'Vacía el aceite de la caja de cambios.',
        'Desmonta la tapa del embrague.',
        'Saca los muelles y los discos del embrague.',
        'Mide el grosor de los discos de fricción y la longitud de los muelles y compáralos con el manual de taller.',
        'Revisa que la campana y el buje no tengan marcas profundas.',
        'Monta con junta nueva, aprieta la tapa a su par y rellena 0,7 L de aceite.',
      ],
      tips: 'Si el embrague patina o la maneta se endurece, revisa también el nivel y el estado del líquido del embrague hidráulico.',
    },
    {
      id: 'silenciador',
      name: 'Silenciador: fibra de vidrio',
      category: 'motor',
      every: 40,
      months: null,
      duration: '45 min',
      difficulty: 2,
      tools: ['Llaves y vasos métricos', 'Taladro y remachadora (si el silenciador va remachado)'],
      parts: ['Relleno de fibra de vidrio para silenciador', 'Remaches o juntas (según silenciador)'],
      torques: [
        { part: 'Tornillos generales de chasis M6', nm: 10 },
        { part: 'Tornillos generales de chasis M8', nm: 25 },
      ],
      steps: [
        'Desmonta el silenciador de la moto.',
        'Abre el silenciador y saca la fibra vieja.',
        'Limpia el tubo interior perforado.',
        'Envuelve el tubo con fibra nueva de forma uniforme.',
        'Cierra el silenciador y móntalo en la moto.',
      ],
      tips: 'Una fibra quemada hace que la moto suene más fuerte y pierda algo de rendimiento.',
    },
    {
      id: 'carburador',
      name: 'Carburador: limpiar y ajustar',
      category: 'motor',
      every: null,
      months: 12,
      duration: '1,5 h',
      difficulty: 3,
      tools: ['Destornilladores', 'Llaves métricas', 'Limpiador de carburadores', 'Aire comprimido'],
      parts: ['Juntas de la cuba (si están dañadas)'],
      torques: [],
      steps: [
        'Cierra la gasolina y desmonta el carburador Keihin PWK 36S AG.',
        'Vacía y limpia la cuba del flotador.',
        'Desmonta y limpia los chiclés con limpiador y aire comprimido. Nunca con alambres: se deforman.',
        'Limpia y aceita la campana del gas.',
        'Monta el carburador y ajusta el ralentí y el tornillo de aire.',
      ],
      tips: 'Si la moto va a estar parada semanas, vacía la cuba: la mezcla vieja deja residuos en los chiclés.',
    },
    {
      id: 'carburador-piezas',
      name: 'Carburador: campana, aguja y válvula',
      category: 'motor',
      every: 100,
      months: null,
      duration: '1,5 h',
      difficulty: 3,
      tools: ['Destornilladores', 'Llaves métricas', 'Limpiador de carburadores'],
      parts: ['Campana del gas', 'Aguja', 'Válvula de aguja del flotador', 'Pulverizador (surtidor de aguja)'],
      torques: [],
      steps: [
        'Desmonta el carburador.',
        'Sustituye la campana del gas, la aguja, la válvula de aguja del flotador y el pulverizador.',
        'Comprueba la altura del flotador.',
        'Monta, ajusta el ralentí y prueba la respuesta del gas.',
      ],
      tips: 'KTM indica cambiar el cuerpo del carburador, el portachiclé y el soporte del flotador a las 200 h.',
    },
    {
      id: 'frenos-revisar',
      name: 'Frenos: pastillas, discos y niveles',
      category: 'frenos',
      every: 10,
      months: null,
      duration: '15 min',
      difficulty: 1,
      tools: ['Linterna', 'Calibre', 'Llave dinamométrica (si hay que desmontar)'],
      parts: ['Pastillas de freno (si están por debajo de 1 mm)'],
      torques: [
        { part: 'Tornillos pinza delantera (M8)', nm: 25, note: 'Loctite 243' },
        { part: 'Tornillos de los discos de freno (M6)', nm: 14 },
        { part: 'Rótula varilla bomba freno trasero (M6)', nm: 10 },
      ],
      steps: [
        'Mira el grosor de las pastillas: mínimo 1 mm de material.',
        'Mide los discos: mínimo 2,5 mm el delantero y 3,5 mm el trasero.',
        'Revisa latiguillos: sin grietas ni fugas.',
        'Comprueba el nivel de líquido de freno delantero, trasero y del embrague.',
        'Comprueba el tacto y el recorrido libre de maneta y pedal.',
      ],
      tips: 'Antes de cada salida mira las pastillas y el nivel de líquido: en campo se gastan rápido con barro.',
    },
    {
      id: 'liquido-frenos',
      name: 'Líquido de frenos',
      category: 'frenos',
      every: 40,
      months: 12,
      duration: '45 min',
      difficulty: 2,
      tools: ['Llave para los purgadores', 'Tubo transparente y botella', 'Jeringuilla', 'Trapos'],
      parts: ['Líquido de frenos DOT 5.1 (Motorex Brake Fluid DOT 5.1)'],
      torques: [
        { part: 'Tornillos pinza delantera (M8)', nm: 25, note: 'Loctite 243' },
      ],
      steps: [
        'Protege pintura y plásticos del líquido de frenos.',
        'Abre el depósito y retira el líquido viejo.',
        'Rellena con DOT 5.1 y purga cada pinza: abre el purgador, acciona maneta o pedal, cierra y suelta. Repite hasta que salga limpio y sin burbujas.',
        'Rellena el depósito delantero hasta 5 mm por debajo del borde. Monta membrana y tapa.',
        'Comprueba el tacto antes de rodar.',
      ],
      tips: 'Usa DOT 5.1 (se puede mezclar con DOT 4). Nunca DOT 5: es de silicona y daña las juntas. El manual pide también cambiar el guardapolvos del bombín trasero cada 40 h.',
    },
    {
      id: 'liquido-embrague',
      name: 'Líquido del embrague hidráulico',
      category: 'transmision',
      every: null,
      months: 12,
      duration: '30 min',
      difficulty: 2,
      tools: ['Jeringuilla de purga', 'Llave para el purgador del bombín', 'Trapos'],
      parts: ['Líquido DOT 5.1'],
      torques: [],
      steps: [
        'Abre la tapa del depósito del embrague en el manillar.',
        'Llena la jeringuilla con DOT 5.1, quita el purgador del bombín del motor y conecta la jeringuilla.',
        'Empuja el líquido desde abajo hasta que en el depósito salga sin burbujas. Retira el sobrante del depósito para que no rebose.',
        'Monta el purgador, ajusta el nivel del depósito y cierra la tapa.',
        'Comprueba que el embrague desembraga bien.',
      ],
      tips: 'En la 250/300 de 2009 el embrague usa líquido de frenos DOT 5.1 (en la 125/200 es aceite mineral: no los confundas).',
    },
    {
      id: 'horquilla-purgar',
      name: 'Horquilla: purgar y limpiar guardapolvos',
      category: 'chasis',
      every: 20,
      months: null,
      duration: '20 min',
      difficulty: 1,
      tools: ['Caballete para dejar la rueda delantera en el aire', 'Destornillador', 'Trapos'],
      parts: ['Spray lubricante para guardapolvos'],
      torques: [],
      steps: [
        'Levanta la moto para que la rueda delantera quede en el aire (horquilla sin carga).',
        'Abre un momento los tornillos de purga de la parte superior de las barras para sacar el aire acumulado y ciérralos.',
        'Baja los guardapolvos, limpia la barra y los retenes de barro y arena, lubrica y vuelve a colocarlos.',
        'Revisa que no haya pérdidas de aceite.',
      ],
      tips: 'Purga la horquilla siempre que notes que endurece durante la salida, sobre todo si cambias mucho de altitud.',
    },
    {
      id: 'horquilla-servicio',
      name: 'Horquilla: mantenimiento completo',
      category: 'chasis',
      every: 80,
      months: 12,
      duration: '3 h (especialista)',
      difficulty: 5,
      tools: ['Herramientas específicas WP', 'Llave dinamométrica'],
      parts: ['Aceite de horquilla SAE 5', 'Retenes y guardapolvos', 'Casquillos (si están gastados)'],
      torques: [
        { part: 'Tornillos tija superior (tija mecanizada, M8)', nm: 17 },
        { part: 'Tornillos tija inferior (tija mecanizada, M8)', nm: 12 },
        { part: 'Tornillos tija superior (tija forjada, M8)', nm: 20 },
        { part: 'Tornillos tija inferior (tija forjada, M8)', nm: 15 },
        { part: 'Tornillos de las botellas de la horquilla (M8)', nm: 15 },
        { part: 'Tornillo eje delantero (M24x1,5)', nm: 45 },
      ],
      steps: [
        'Desmonta la rueda delantera y las barras de la horquilla.',
        'Cambia aceite, retenes y guardapolvos y revisa los casquillos.',
        'Monta las barras a la misma altura y aprieta las tijas a su par (según tija mecanizada o forjada).',
        'Monta la rueda: eje delantero a 45 N·m, tornillos de las botellas a 15 N·m.',
        'Vuelve a los reglajes estándar: compresión 22 clics, rebote 22 clics.',
      ],
      tips: 'Uso de ocio: al menos una vez al año. Suele merecer la pena hacerlo en un especialista de suspensiones.',
    },
    {
      id: 'amortiguador',
      name: 'Amortiguador: mantenimiento completo',
      category: 'chasis',
      every: null,
      months: 24,
      duration: '3 h (especialista)',
      difficulty: 5,
      tools: ['Herramientas específicas WP', 'Llave dinamométrica'],
      parts: ['Aceite de amortiguador', 'Retenes', 'Nitrógeno para el depósito'],
      torques: [
        { part: 'Tornillo superior del amortiguador (M12)', nm: 80, note: 'Loctite 243' },
        { part: 'Tornillo inferior del amortiguador (M12)', nm: 80, note: 'Loctite 243' },
        { part: 'Tornillo anillo de precarga del muelle (M6)', nm: 8 },
      ],
      steps: [
        'Desmonta el amortiguador de la moto.',
        'Llévalo a un especialista WP: cambio de aceite, retenes y recarga de nitrógeno.',
        'Monta con Loctite 243 y aprieta los tornillos superior e inferior a 80 N·m.',
        'Ajusta la precarga del muelle para un sag estático de 35 mm y en marcha de 105 mm.',
      ],
      tips: 'Uso de ocio: cada 2 años. En uso intenso o competición, cada 80 h.',
    },
    {
      id: 'radios-ruedas',
      name: 'Radios, llantas y rodamientos',
      category: 'chasis',
      every: 20,
      months: null,
      first: 10,
      duration: '20 min',
      difficulty: 2,
      tools: ['Llave de radios', 'Llave dinamométrica para radios (5 N·m)', 'Destornillador (para golpear los radios)'],
      parts: [],
      torques: [
        { part: 'Radios (M4,5 / M5)', nm: 5 },
        { part: 'Tornillo eje delantero (M24x1,5)', nm: 45 },
        { part: 'Tuerca del eje trasero (M20x1,5)', nm: 80 },
      ],
      steps: [
        'Golpea cada radio con la hoja de un destornillador: debe sonar claro. Un sonido apagado indica radio flojo.',
        'Aprieta los radios flojos a 5 N·m. Si hay muchos, lleva la rueda a centrar.',
        'Comprueba el tornillo de seguridad de la llanta.',
        'Con la rueda en el aire, muévela lateralmente: no debe haber holgura en los rodamientos.',
        'Revisa la presión: 1,0 bar en campo.',
      ],
      tips: 'Con ruedas nuevas, revisa los radios tras los primeros 30 minutos: se aflojan rápido.',
    },
    {
      id: 'direccion-basculante',
      name: 'Dirección y basculante',
      category: 'chasis',
      every: 40,
      months: 12,
      first: 10,
      duration: '1 h',
      difficulty: 3,
      tools: ['Caballete', 'Llave dinamométrica', 'Grasa'],
      parts: ['Grasa para rodamientos'],
      torques: [
        { part: 'Tornillo superior de la pipa de dirección (M20x1,5)', nm: 10 },
        { part: 'Tornillo inferior de la pipa de dirección (M20x1,5)', nm: 60, note: 'Loctite 243' },
        { part: 'Tuerca eje del basculante (M16x1,5)', nm: 100 },
        { part: 'Tornillos soporte del manillar (M10)', nm: 40, note: 'Loctite 243' },
        { part: 'Tornillos abrazadera del manillar (M8)', nm: 20 },
      ],
      steps: [
        'Con la rueda delantera en el aire, comprueba que no hay holgura en la pipa y que la dirección gira suave.',
        'Si hay holgura, ajusta los rodamientos de dirección.',
        'Una vez al año, desmonta, limpia y engrasa los rodamientos de dirección y sus juntas.',
        'Revisa los rodamientos del basculante: sin holgura lateral.',
      ],
      tips: 'El lavado a presión se lleva la grasa de los rodamientos: no apuntes la pistola a pipa, basculante ni bujes.',
    },
    {
      id: 'refrigeracion',
      name: 'Refrigeración: fugas y anticongelante',
      category: 'refrigeracion',
      every: 40,
      months: 12,
      first: 10,
      duration: '15 min',
      difficulty: 1,
      tools: ['Densímetro de anticongelante', 'Trapo (para abrir el tapón)'],
      parts: ['Refrigerante 50 % anticongelante (si hay que rellenar)'],
      torques: [
        { part: 'Tapón de vaciado tapa bomba de agua (M10x1)', nm: 15 },
      ],
      steps: [
        'Con el motor frío, abre el tapón del radiador.',
        'El refrigerante debe cubrir 10 mm por encima de las aletas del radiador.',
        'Comprueba la protección del anticongelante: mínimo -25 °C.',
        'Revisa manguitos y radiadores: sin fugas ni golpes.',
        'Si has vaciado el circuito, rellena 1,2 L y purga el aire.',
      ],
      tips: 'Nunca abras el tapón con el motor caliente: el líquido sale a presión y quema.',
    },
    {
      id: 'mandos-tornilleria',
      name: 'Cables, mandos y tornillería',
      category: 'chasis',
      every: 40,
      months: null,
      first: 10,
      duration: '30 min',
      difficulty: 1,
      tools: ['Juego de llaves y vasos métricos', 'Llave dinamométrica', 'Spray lubricante para cables'],
      parts: [],
      torques: [
        { part: 'Tornillos del subchasis (M8)', nm: 35, note: 'Loctite 243' },
        { part: 'Tornillos de anclaje del motor (M10)', nm: 60 },
        { part: 'Tirante del motor (M8)', nm: 33 },
        { part: 'Tornillo del caballete lateral (M8)', nm: 40, note: 'Loctite 243' },
        { part: 'Palanca de cambio (M6)', nm: 14, note: 'Loctite 243' },
        { part: 'Pedal de arranque (M8)', nm: 25, note: 'Loctite 243' },
      ],
      steps: [
        'Lubrica y ajusta los cables del gas; deben ir suaves y sin dobleces.',
        'Comprueba el apriete de pedal de arranque y palanca de cambio.',
        'Revisa el apriete de toda la tornillería del chasis: tijas, ejes, basculante, amortiguador, subchasis.',
        'Revisa el escape: sin fugas y bien sujeto.',
      ],
      tips: 'Una enduro vibra mucho: la tornillería se afloja más que en una moto de carretera.',
    },
    {
      id: 'motor-bajo',
      name: 'Cigüeñal, biela y caja de cambios',
      category: 'motor',
      every: 120,
      months: null,
      duration: 'Taller',
      difficulty: 5,
      tools: ['Taller con herramientas específicas KTM'],
      parts: ['Rodamientos de cigüeñal', 'Rodamiento de biela', 'Juntas y retenes del cárter'],
      torques: [
        { part: 'Tuerca del volante magnético (M12x1)', nm: 60 },
        { part: 'Tuerca piñón primario (M18x1,5, rosca a izquierdas)', nm: 150, note: 'Loctite 2701' },
        { part: 'Tuerca buje interior del embrague (M18x1,5)', nm: 100, note: 'Loctite 2701' },
        { part: 'Tornillos del cárter (M6)', nm: 10 },
      ],
      steps: [
        'Abrir el motor y sustituir los rodamientos de biela.',
        'Revisar y sustituir los rodamientos de bancada del cigüeñal.',
        'Revisar la caja de cambios, el mecanismo de cambio y sus rodamientos.',
      ],
      tips: 'Uso de ocio: rodamientos de biela y revisión de caja a las 120 h; rodamientos de bancada entre 80 y 120 h. Trabajo de taller.',
    },
  ],
});
