// Datos técnicos de la KTM 1290 Super Adventure S (2022).
// Plan de mantenimiento, capacidades y pares del manual de usuario oficial 2022 (art. 3214538en).
// Verifica siempre los valores críticos con el manual de taller de tu unidad.

BIKES.push({
  id: 'superadventure1290s',
  brand: 'ktm',
  short: 'SUPER ADV S',
  name: 'KTM 1290 Super Adventure S',
  years: '2022',
  unit: 'km',
  before: 1000,
  source: 'el manual de usuario oficial de la KTM 1290 Super Adventure S 2022',
  specs: [
    { label: 'Motor', value: 'V2 a 75°, 1.301 cc, DOHC 4 válvulas por cilindro, cárter seco' },
    { label: 'Aceite motor', value: 'SAE 10W-50 (≥ 0 °C) · SAE 5W-40 (< 0 °C)' },
    { label: 'Capacidad aceite', value: '3,6 L con filtro (primero ≈ 3,0 L y completar hasta la marca superior)' },
    { label: 'Bujías', value: 'Central NGK LKAR9DI-10 · Exterior NGK LMAR7DI-10 · distancia 1,0 mm' },
    { label: 'Holgura válvulas (20 °C)', value: 'Admisión 0,10–0,15 mm · Escape 0,25–0,30 mm' },
    { label: 'Refrigerante', value: '2 L' },
    { label: 'Líquido de frenos y embrague', value: 'DOT 4 / DOT 5.1' },
    { label: 'Ralentí', value: '1.280 – 1.480 rpm' },
    { label: 'Cadena', value: '525 X-ring (5/8 x 5/16") · 17:42' },
    { label: 'Tensión cadena', value: 'Destornillador en el hueco de la guía: queda paralelo al suelo con ligera presión (moto en caballete central)' },
    { label: 'Desgaste cadena', value: 'Máx. 272 mm en 18 rodillos (tirando con 15 kg)' },
    { label: 'Neumáticos', value: '120/70 ZR19 · 170/60 ZR17' },
    { label: 'Presión neumáticos', value: 'Delantero 2,4 bar · Trasero 2,9 bar (en frío; solo, con pasajero o con carga)' },
    { label: 'Frenos: límites', value: 'Pastillas mín. 1 mm · Disco del. mín. 4 mm · Disco tras. mín. 4,5 mm' },
    { label: 'Suspensión', value: 'WP semiactiva · sag estático 25 mm' },
    { label: 'Aceite horquilla', value: 'Barra izquierda 695 ml · derecha 430 ml · SAE 4' },
    { label: 'Batería', value: 'YTZ14S · 12 V 11,2 Ah' },
    { label: 'Depósito', value: '23 L (reserva ≈ 5 L)' },
  ],
  tasks: [
    {
      id: 'aceite',
      name: 'Aceite, filtro y tamices',
      category: 'motor',
      every: 15000,
      months: 12,
      first: 1000,
      duration: '1 h',
      difficulty: 2,
      tools: [
        'Herramientas para quitar el cubrecárter y la tapa de los tapones',
        'Llave para los 2 tapones de vaciado (M20x1,5, con imán y tamiz)',
        'Llave para los tornillos M5 de la tapa del filtro de aceite',
        'Alicates de circlip de apertura inversa para sacar el filtro',
        'Llave dinamométrica de rango bajo (5–25 N·m)',
        'Bandeja de vaciado (mín. 5 L), embudo, guantes y trapos',
      ],
      parts: [
        '3,6 L de aceite SAE 10W-50 (5W-40 si ruedas por debajo de 0 °C)',
        'Filtro de aceite',
        'Juntas tóricas de los tapones de vaciado y de la tapa del filtro',
      ],
      torques: [
        { part: 'Tapones de vaciado de aceite (M20x1,5)', nm: 20 },
        { part: 'Tornillos tapa del filtro de aceite (M5x16)', nm: 6 },
      ],
      steps: [
        'Calienta el motor unos minutos para que el aceite fluya mejor. Cuidado: el aceite quema.',
        'Quita el cubrecárter y la tapa de los tapones de vaciado.',
        'Pon la moto sobre el caballete lateral en suelo horizontal y la bandeja bajo el motor.',
        'Quita los 2 tapones de vaciado con sus imanes, juntas tóricas y tamices.',
        'Quita los tornillos de la tapa del filtro, retira la tapa con su junta y saca el filtro.',
        'Deja escurrir todo el aceite y limpia bien piezas y superficies de apoyo.',
        'Mete el filtro nuevo a mano, engrasa la junta tórica de la tapa, móntala y aprieta los tornillos M5 a 6 N·m.',
        'Limpia a fondo imanes y tamices; monta los tapones de vaciado y apriétalos a 20 N·m.',
        'Ten a mano los 3,6 L. Rellena en dos veces: primero ≈ 3,0 L por el tapón de llenado.',
        'Arranca el motor y comprueba que no haya fugas.',
        'Añade el resto hasta la marca superior del visor. Con el motor caliente y la moto vertical, el nivel debe quedar en la zona superior.',
        'Vuelve a montar la tapa de los tapones y el cubrecárter.',
      ],
      tips: 'El primer cambio es a los 1.000 km. El indicador de servicio del cuadro lo pone a cero el taller con la herramienta de diagnosis KTM.',
    },
    {
      id: 'filtro-aire',
      name: 'Filtro de aire: sustituir',
      category: 'motor',
      every: 15000,
      months: null,
      duration: '1 h',
      difficulty: 3,
      tools: ['Herramientas para desmontar el acceso a la caja del filtro', 'Llave dinamométrica de rango bajo', 'Aspirador o trapos'],
      parts: ['Filtro de aire nuevo'],
      torques: [
        { part: 'Tornillos largos tapa caja del filtro (EJOT PT 60x30)', nm: 2.5, note: 'autorroscantes en plástico: aprieta con suavidad' },
        { part: 'Tornillos cortos tapa caja del filtro (EJOT PT 60x20)', nm: 2 },
      ],
      steps: [
        'Desmonta las piezas que dan acceso a la caja del filtro según el manual.',
        'Quita la tapa de la caja del filtro y saca el filtro usado fijándote en su posición.',
        'Limpia la caja del filtro sin que entre suciedad en las admisiones.',
        'Coloca el filtro nuevo bien asentado en todo su contorno.',
        'Monta la tapa: tornillos largos a 2,5 N·m y cortos a 2 N·m.',
      ],
      tips: 'Si ruedas mucho por pistas con polvo, revísalo antes: un filtro sucio hace perder potencia y subir el consumo.',
    },
    {
      id: 'bujias',
      name: 'Bujías: sustituir',
      category: 'electrico',
      every: 30000,
      months: null,
      duration: '2 h (hay que quitar el depósito)',
      difficulty: 4,
      tools: [
        'Herramientas para desmontar el depósito de gasolina',
        'Llave de bujías de pared fina y larga (para cada tipo de bujía)',
        'Alargo y articulación',
        'Llave dinamométrica de rango bajo (10–25 N·m)',
        'Galgas para la distancia entre electrodos',
      ],
      parts: ['2 bujías NGK LKAR9DI-10 (centrales)', '2 bujías NGK LMAR7DI-10 (exteriores)'],
      torques: [
        { part: 'Bujía central (M12x1,5)', nm: 18 },
        { part: 'Bujía exterior (M10x1)', nm: 11 },
        { part: 'Tornillo de la bobina (M6)', nm: 8 },
      ],
      steps: [
        'Con el motor frío, desmonta el depósito de gasolina según el manual.',
        'Suelta y retira las bobinas tirando recto; sopla alrededor de cada bujía antes de sacarla.',
        'Saca las bujías. Cada cilindro lleva dos: central (M12) y exterior (M10).',
        'Comprueba la distancia entre electrodos de las nuevas: 1,0 mm.',
        'Enrosca a mano y aprieta: centrales a 18 N·m, exteriores a 11 N·m.',
        'Monta las bobinas (tornillos a 8 N·m) y el depósito.',
      ],
      tips: 'Aprovecha que el depósito está fuera para revisar la holgura de válvulas y cambiar las membranas SAS (también a los 30.000 km).',
    },
    {
      id: 'valvulas',
      name: 'Holgura de válvulas',
      category: 'motor',
      every: 30000,
      months: null,
      duration: '4–6 h (taller)',
      difficulty: 5,
      tools: ['Galgas de espesores (0,05–0,40 mm)', 'Juego de llaves y vasos métricos, Torx y Allen', 'Llave dinamométrica'],
      parts: ['Juntas de las tapas de válvulas (si están dañadas)', 'Pastillas de reglaje de la medida necesaria'],
      torques: [
        { part: 'Tornillos tapa de válvulas (M6)', nm: 10 },
        { part: 'Bujía central (M12x1,5)', nm: 18 },
        { part: 'Bujía exterior (M10x1)', nm: 11 },
      ],
      steps: [
        'Con el motor frío (≈ 20 °C), desmonta depósito y bujías.',
        'Desmonta las tapas de válvulas.',
        'Gira el cigüeñal hasta el punto muerto superior de compresión del cilindro que vayas a medir.',
        'Mide cada válvula: admisión 0,10–0,15 mm, escape 0,25–0,30 mm.',
        'Si alguna está fuera de rango hay que cambiar la pastilla de reglaje (trabajo de taller).',
        'Monta las tapas y aprieta los tornillos M6 a 10 N·m.',
      ],
      tips: 'Es la revisión grande de los 30.000 km. Si no tienes experiencia con motores de distribución por cadena, déjala al taller.',
    },
    {
      id: 'sas',
      name: 'Membranas SAS (aire secundario)',
      category: 'motor',
      every: 30000,
      months: null,
      duration: '30 min (con el depósito fuera)',
      difficulty: 2,
      tools: ['Llaves Torx/Allen', 'Llave dinamométrica de rango bajo'],
      parts: ['Membranas SAS nuevas'],
      torques: [
        { part: 'Tornillos placa SAS en la caja del filtro (EJOT PT K50x16)', nm: 2 },
        { part: 'Tornillos brida SAS (M6x12)', nm: 10 },
      ],
      steps: [
        'Con el depósito desmontado, localiza las válvulas del sistema de aire secundario (SAS).',
        'Sustituye las membranas respetando su posición.',
        'Comprueba que los manguitos del sistema no estén agrietados.',
        'Monta y aprieta los tornillos a su par.',
      ],
      tips: 'KTM pide cambiarlas cada 30.000 km, junto con bujías y válvulas.',
    },
    {
      id: 'cadena-engrasar',
      name: 'Cadena: limpiar y engrasar',
      category: 'transmision',
      every: 1000,
      months: null,
      duration: '20 min',
      difficulty: 1,
      tools: ['Caballete central', 'Limpiador de cadenas y cepillo', 'Spray de cadena', 'Trapos'],
      parts: ['Limpiador y spray de cadena'],
      torques: [],
      steps: [
        'Sube la moto al caballete central y pon punto muerto.',
        'Quita la suciedad con limpiador de cadenas compatible con retenes X-ring y deja secar.',
        'Aplica el spray por la cara interior mientras giras la rueda.',
        'Retira el exceso: no debe llegar grasa al neumático ni al disco.',
      ],
      tips: 'Tras pistas con barro o lluvia, límpiala y engrásala aunque no toque: el barro con grasa desgasta el kit de arrastre muy rápido.',
    },
    {
      id: 'cadena-tensar',
      name: 'Cadena: tensión y desgaste',
      category: 'transmision',
      every: 15000,
      months: null,
      first: 1000,
      duration: '30 min',
      difficulty: 2,
      tools: [
        'Caballete central',
        'Destornillador (para medir la tensión)',
        'Llave para la tuerca del eje trasero (M25x1,5)',
        'Llaves para las contratuercas y tornillos tensores',
        'Llave dinamométrica (hasta 100 N·m)',
        'Metro y un peso o dinamómetro de 15 kg',
      ],
      parts: [],
      torques: [
        { part: 'Tuerca del eje trasero (M25x1,5)', nm: 90, note: 'rosca engrasada' },
        { part: 'Tuercas de la corona (M10x1,25)', nm: 50, note: 'Loctite 243' },
        { part: 'Tornillos patín de cadena (M5x10)', nm: 5 },
      ],
      steps: [
        'Sube la moto al caballete central y pon punto muerto.',
        'Mete un destornillador en el hueco de la guía de cadena, entre la cadena y el basculante, y empújalo un poco hacia arriba.',
        'La tensión es correcta si el destornillador queda paralelo al suelo con una ligera presión. Si apunta hacia abajo, está demasiado tensa; hacia arriba, floja.',
        'Para ajustar: afloja la tuerca del eje trasero y las contratuercas de los tensores.',
        'Gira los tornillos tensores izquierdo y derecho para que las marcas de ambos lados queden en la misma posición (así la rueda va alineada).',
        'Aprieta las contratuercas y la tuerca del eje a 90 N·m con la rosca engrasada.',
        'Desgaste: tirando del tramo inferior con 15 kg, 18 rodillos del tramo superior no deben medir más de 272 mm. Si es así, cambia cadena, piñón y corona juntos.',
      ],
      tips: 'La cadena no se desgasta por igual: mide en varios puntos girando la rueda.',
    },
    {
      id: 'frenos-revisar',
      name: 'Frenos: pastillas y discos',
      category: 'frenos',
      every: 15000,
      months: null,
      first: 1000,
      duration: '30 min',
      difficulty: 1,
      tools: ['Linterna', 'Calibre (grosor de discos)', 'Llave dinamométrica (si hay que desmontar)'],
      parts: ['Pastillas de freno (si están por debajo de 1 mm)'],
      torques: [
        { part: 'Tornillos pinza de freno delantera (M10x1,5x55)', nm: 45, note: 'Loctite 243' },
        { part: 'Tornillos disco delantero (M6)', nm: 14, note: 'Loctite 243' },
        { part: 'Tornillos disco trasero (M6)', nm: 14, note: 'Loctite 243' },
        { part: 'Tornillo banjo latiguillo de freno (M10x1)', nm: 25 },
      ],
      steps: [
        'Mira el grosor de cada pastilla: mínimo 1 mm de material, sin grietas ni daños.',
        'Mide los discos: mínimo 4 mm el delantero y 4,5 mm el trasero.',
        'Revisa que los latiguillos no tengan grietas ni fugas.',
        'Comprueba el nivel de líquido de freno delantero, trasero y del embrague hidráulico.',
      ],
      tips: 'Si cambias pastillas, bombea la maneta/pedal antes de mover la moto hasta recuperar el tacto.',
    },
    {
      id: 'liquido-frenos',
      name: 'Líquido de frenos y embrague',
      category: 'frenos',
      every: null,
      months: 24,
      duration: '1,5 h',
      difficulty: 3,
      tools: ['Llave para los purgadores', 'Tubo transparente y botella', 'Jeringuilla o purgador por vacío', 'Trapos'],
      parts: ['1 L de líquido DOT 4 / DOT 5.1 (frenos y embrague hidráulico)'],
      torques: [
        { part: 'Tornillo banjo latiguillo de freno (M10x1)', nm: 25 },
        { part: 'Tapa depósito freno trasero', nm: 3.5 },
        { part: 'Tornillos tapa depósito freno delantero', nm: 1 },
      ],
      steps: [
        'Protege pintura y plásticos: el líquido de frenos los ataca.',
        'Retira el líquido viejo del depósito delantero, rellena con nuevo y purga pinza a pinza hasta que salga limpio sin burbujas.',
        'No dejes que el depósito se vacíe durante la purga.',
        'Repite en el freno trasero y en el embrague hidráulico.',
        'Ajusta los niveles, cierra las tapas (delantera 1 N·m, trasera 3,5 N·m) y comprueba el tacto.',
      ],
      tips: 'Con ABS, si entra aire en el modulador hace falta la herramienta de diagnosis del taller para purgarlo del todo.',
    },
    {
      id: 'neumaticos',
      name: 'Neumáticos: estado y presión',
      category: 'chasis',
      every: 15000,
      months: null,
      first: 1000,
      duration: '10 min',
      difficulty: 1,
      tools: ['Manómetro', 'Compresor', 'Medidor de profundidad de dibujo'],
      parts: [],
      torques: [
        { part: 'Eje delantero (M25x1,5)', nm: 45, note: 'rosca engrasada' },
        { part: 'Tornillos de las botellas de la horquilla (M8)', nm: 15 },
        { part: 'Tuerca del eje trasero (M25x1,5)', nm: 90, note: 'rosca engrasada' },
      ],
      steps: [
        'Mide la presión en frío: 2,4 bar delante y 2,9 bar detrás (igual solo, con pasajero o con carga).',
        'Revisa la profundidad del dibujo y busca cortes, grietas, deformaciones o clavos.',
      ],
      tips: 'Si usas neumáticos de campo o bajas presión para pistas, vuelve a la presión de carretera antes de salir al asfalto.',
    },
    {
      id: 'direccion-suspension',
      name: 'Dirección, rodamientos y suspensiones',
      category: 'chasis',
      every: 15000,
      months: null,
      first: 1000,
      duration: '45 min',
      difficulty: 2,
      tools: ['Caballete central', 'Llave dinamométrica', 'Trapo limpio'],
      parts: [],
      torques: [
        { part: 'Tornillos tija superior (M8x35)', nm: 20 },
        { part: 'Tornillos tija inferior (M8x35)', nm: 15 },
        { part: 'Tornillo de apriete de la pipa (M8x35)', nm: 20 },
        { part: 'Tornillo superior de la pipa de dirección (M22x1,5)', nm: 18 },
        { part: 'Tornillos amortiguador superior e inferior (M14x1,5)', nm: 80, note: 'rosca engrasada' },
      ],
      steps: [
        'Con la rueda delantera en el aire, comprueba que no hay holgura en la pipa y que la dirección gira suave.',
        'Mueve las ruedas lateralmente: no debe haber holgura en los rodamientos.',
        'Revisa que horquilla y amortiguador no pierdan aceite.',
        'Limpia los guardapolvos de las barras de la horquilla.',
      ],
      tips: 'La suspensión es semiactiva (electrónica): el servicio interno de horquilla y amortiguador lo debe hacer un taller KTM/WP.',
    },
    {
      id: 'refrigerante',
      name: 'Refrigerante: sustituir',
      category: 'refrigeracion',
      every: null,
      months: 48,
      duration: '1 h',
      difficulty: 3,
      tools: ['Bandeja', 'Embudo', 'Llave dinamométrica de rango bajo'],
      parts: ['2 L de refrigerante'],
      torques: [
        { part: 'Tornillo de purga de refrigerante en la culata (M6x10)', nm: 6 },
      ],
      steps: [
        'Hazlo con el motor frío: el sistema está a presión y el líquido quema.',
        'Vacía el circuito según el manual y recoge el refrigerante (es tóxico).',
        'Rellena con refrigerante nuevo y purga el aire del circuito.',
        'Arranca, deja que se caliente y comprueba que el ventilador se activa.',
        'Con el motor frío, el nivel del vaso de expansión debe quedar entre MIN y MAX.',
      ],
      tips: 'En cada revisión comprueba el nivel del vaso de expansión (motor frío) y la protección del anticongelante.',
    },
    {
      id: 'engrase-tornilleria',
      name: 'Engrase, manguitos y tornillería',
      category: 'chasis',
      every: 15000,
      months: 12,
      first: 1000,
      duration: '45 min',
      difficulty: 1,
      tools: ['Juego de llaves y vasos métricos, Torx y Allen', 'Llave dinamométrica', 'Grasa y spray lubricante'],
      parts: ['Grasa'],
      torques: [
        { part: 'Tornillos abrazadera del manillar (M8x25)', nm: 20 },
        { part: 'Tornillos soporte del manillar (M10x35)', nm: 40, note: 'Loctite 243' },
        { part: 'Tornillo del caballete lateral (M10)', nm: 40, note: 'Loctite 243' },
        { part: 'Tornillos del subchasis (M10x20)', nm: 45 },
        { part: 'Tornillos generales de chasis M6', nm: 10 },
        { part: 'Tornillos generales de chasis M8', nm: 25 },
      ],
      steps: [
        'Engrasa las piezas móviles: caballetes, manetas, articulaciones de pedales.',
        'Vacía los tubos de drenaje.',
        'Revisa manguitos de gasolina, refrigeración y respiraderos: sin grietas, fugas ni pliegues.',
        'Comprueba el apriete de los tornillos y tuercas de seguridad accesibles.',
      ],
      tips: 'KTM lo marca como trabajo recomendado en cada revisión y al menos una vez al año.',
    },
    {
      id: 'diagnosis',
      name: 'Diagnosis, radar y sensores (taller)',
      category: 'electrico',
      every: 15000,
      months: 12,
      first: 1000,
      duration: '30 min (taller)',
      difficulty: 5,
      tools: ['Herramienta de diagnosis KTM (sólo concesionario/taller)'],
      parts: [],
      torques: [
        { part: 'Tornillos del sensor de radar delantero (M6x20)', nm: 5 },
      ],
      steps: [
        'Leer y borrar la memoria de errores con la herramienta de diagnosis KTM.',
        'Programar el sensor del eje de cambio (quickshifter).',
        'Comprobar la alineación del sensor de radar delantero (control de crucero adaptativo).',
        'Comprobar el funcionamiento del sistema eléctrico, el ventilador y la presión de gasolina.',
        'Poner a cero el indicador de servicio.',
      ],
      tips: 'Sin la herramienta de diagnosis no se puede resetear el aviso de servicio ni alinear el radar: pídelo en la revisión anual.',
    },
    {
      id: 'bateria',
      name: 'Batería: revisar',
      category: 'electrico',
      every: null,
      months: 12,
      duration: '10 min',
      difficulty: 1,
      tools: ['Polímetro', 'Llave para los bornes', 'Llave dinamométrica de rango bajo'],
      parts: ['Batería YTZ14S (si hay que cambiarla)'],
      torques: [
        { part: 'Tornillos bornes de batería (M6x12)', nm: 4.5 },
      ],
      steps: [
        'Mide la tensión con la moto apagada: 12,6 V o más = cargada; menos de 12,4 V = cárgala.',
        'Con el motor a unas 5.000 rpm debe marcar entre 13,5 y 15 V.',
        'Limpia y protege los bornes si hay sulfato. Apriétalos a 4,5 N·m.',
      ],
      tips: 'Con tanta electrónica (radar, suspensión, TFT) la batería sufre si la moto está parada: usa un mantenedor de carga.',
    },
  ],
});
