// Datos técnicos de la KTM 1290 Super Duke R (2017).
// Plan de mantenimiento, capacidades y pares del manual de usuario oficial 2017 (art. 3213534es/en).
// Verifica siempre los valores críticos con el manual de taller de tu unidad.

BIKES.push({
  id: 'superduke1290r',
  brand: 'ktm',
  short: 'SUPER DUKE',
  name: 'KTM 1290 Super Duke R',
  years: '2017',
  unit: 'km',
  before: 1000,
  source: 'el manual de usuario oficial de la KTM 1290 Super Duke R 2017',
  specs: [
    { label: 'Motor', value: 'V2 a 75°, 1.301 cc, DOHC 4 válvulas por cilindro, cárter seco' },
    { label: 'Aceite motor', value: 'SAE 10W-50 (≥ 0 °C) · SAE 5W-40 (< 0 °C)' },
    { label: 'Capacidad aceite', value: '3,5 L con filtro (primero ≈ 3,0 L y completar hasta la marca superior)' },
    { label: 'Bujías', value: 'Interior NGK LKAR9BI-10 · Exterior NGK LMAR7DI-10 · distancia 1,0 mm' },
    { label: 'Holgura válvulas (20 °C)', value: 'Admisión 0,10–0,15 mm · Escape 0,25–0,30 mm' },
    { label: 'Refrigerante', value: '3,2 L' },
    { label: 'Líquido de frenos y embrague', value: 'DOT 4 / DOT 5.1' },
    { label: 'Ralentí', value: '1.400 – 1.600 rpm' },
    { label: 'Cadena', value: '525 X-ring (5/8 x 5/16") · 17:38 · sin eslabón de cierre' },
    { label: 'Desgaste cadena', value: 'Máx. 272 mm en 18 rodillos (tirando con 15 kg)' },
    { label: 'Neumáticos', value: '120/70 ZR17 · 190/55 ZR17' },
    { label: 'Presión neumáticos', value: 'Delantero 2,5 bar · Trasero 2,5 bar (en frío, solo)' },
    { label: 'Frenos: límites', value: 'Pastillas mín. 1 mm · Discos mín. 4,5 mm (del. y tras.)' },
    { label: 'Aceite horquilla', value: '680 ml por barra · SAE 4' },
    { label: 'Batería', value: 'YTX14-BS · 12 V 12 Ah' },
    { label: 'Depósito', value: '18 L (reserva ≈ 3,6 L)' },
  ],
  tasks: [
    {
      id: 'aceite',
      name: 'Aceite, filtro y tamices',
      category: 'motor',
      every: 15000,
      months: 12,
      first: 1000,
      duration: '1 h',
      difficulty: 2,
      tools: [
        'Llave para los 2 tapones de vaciado (M20x1,5, llevan imán y tamiz)',
        'Llave para los tornillos M5 de la tapa del filtro de aceite',
        'Alicates de circlip de apertura inversa (KTM 51012011000) para sacar el filtro',
        'Llave dinamométrica de rango bajo (5–25 N·m)',
        'Bandeja de vaciado (mín. 5 L)',
        'Embudo, guantes y trapos',
      ],
      parts: [
        '3,5 L de aceite SAE 10W-50 (5W-40 si ruedas por debajo de 0 °C)',
        'Filtro de aceite',
        'Juntas tóricas de los tapones de vaciado y de la tapa del filtro',
      ],
      torques: [
        { part: 'Tapones de vaciado de aceite (M20x1,5)', nm: 20 },
        { part: 'Tornillos tapa del filtro de aceite (M5)', nm: 6 },
      ],
      steps: [
        'Calienta el motor unos minutos para que el aceite fluya mejor. Cuidado: el aceite quema.',
        'Pon la moto sobre el caballete lateral en suelo horizontal y la bandeja bajo el motor.',
        'Quita los 2 tapones de vaciado con sus imanes, juntas tóricas y tamices.',
        'Quita los tornillos de la tapa del filtro y retira la tapa con su junta tórica.',
        'Saca el filtro de su alojamiento con los alicates de circlip inversos.',
        'Deja escurrir todo el aceite. Limpia bien piezas y superficies de apoyo.',
        'Mete el filtro nuevo a mano, sin herramientas.',
        'Engrasa la junta tórica de la tapa, móntala y aprieta los tornillos M5 a 6 N·m.',
        'Limpia a fondo los imanes y los tamices de los tapones de vaciado.',
        'Monta los tapones de vaciado con imán, juntas y tamiz y apriétalos a 20 N·m.',
        'Rellena en dos veces: primero ≈ 3,0 L por el tapón de llenado y ciérralo.',
        'Arranca el motor y comprueba que no haya fugas.',
        'Añade el resto de aceite hasta la marca superior del visor (3,5 L en total).',
        'Con el motor caliente, moto vertical y 1 minuto después de apagarlo, el nivel debe estar en la zona superior del visor.',
      ],
      tips: 'KTM también pide a los 1.000 km el primer cambio. El indicador de servicio del cuadro solo se resetea con la herramienta de diagnosis KTM (taller).',
    },
    {
      id: 'filtro-aire',
      name: 'Filtro de aire: sustituir',
      category: 'motor',
      every: 15000,
      months: null,
      duration: '1 h',
      difficulty: 3,
      tools: [
        'Destornilladores/llaves para desmontar la tapa de la caja del filtro',
        'Llave dinamométrica de rango bajo',
        'Aspirador o trapos para limpiar la caja',
      ],
      parts: ['Filtro de aire nuevo'],
      torques: [
        { part: 'Tornillos tapa caja del filtro (EJOT PT K60)', nm: 2, note: 'tornillos autorroscantes en plástico: aprieta con suavidad' },
      ],
      steps: [
        'Desmonta las piezas que dan acceso a la caja del filtro según el manual (asiento/depósito según tu unidad).',
        'Quita la tapa de la caja del filtro.',
        'Saca el filtro usado fijándote en su posición.',
        'Limpia la caja del filtro sin que entre suciedad en las admisiones.',
        'Coloca el filtro nuevo bien asentado en todo su contorno.',
        'Monta la tapa y aprieta sus tornillos a 2 N·m.',
      ],
      tips: 'Aprovecha el desmontaje del filtro para cambiar las bujías y revisar válvulas cuando toque (cada 30.000 km).',
    },
    {
      id: 'bujias',
      name: 'Bujías: sustituir',
      category: 'electrico',
      every: 30000,
      months: null,
      duration: '1,5 h (con el filtro de aire fuera)',
      difficulty: 4,
      tools: [
        'Llave de bujías de pared fina y larga (para cada tipo de bujía)',
        'Alargo y articulación',
        'Llave dinamométrica de rango bajo (10–25 N·m)',
        'Galgas para comprobar la distancia entre electrodos',
      ],
      parts: [
        '2 bujías NGK LKAR9BI-10 (interiores)',
        '2 bujías NGK LMAR7DI-10 (exteriores)',
      ],
      torques: [
        { part: 'Bujía interior (M12x1,5)', nm: 18 },
        { part: 'Bujía exterior (M10x1)', nm: 11 },
      ],
      steps: [
        'Con el motor frío, desmonta el filtro de aire (ver "Filtro de aire").',
        'Desconecta y retira las pipas/bobinas tirando recto, sin girarlas con fuerza.',
        'Sopla con aire comprimido alrededor de cada bujía antes de sacarla para que no caiga suciedad al cilindro.',
        'Afloja y saca las bujías. Cada cilindro lleva dos: interior (M12) y exterior (M10).',
        'Comprueba la distancia entre electrodos de las nuevas: 1,0 mm.',
        'Enrosca cada bujía a mano hasta el tope para no cruzar la rosca.',
        'Aprieta con la dinamométrica: interiores (M12x1,5) 18 N·m, exteriores (M10x1) 11 N·m.',
        'Monta las pipas/bobinas hasta notar que encajan y vuelve a montar el filtro de aire.',
      ],
      tips: 'No mezcles las bujías: la interior y la exterior son de tipo y grado térmico distintos.',
    },
    {
      id: 'valvulas',
      name: 'Holgura de válvulas',
      category: 'motor',
      every: 30000,
      months: null,
      duration: '4–6 h (taller)',
      difficulty: 5,
      tools: [
        'Galgas de espesores (0,05–0,40 mm)',
        'Juego de llaves y vasos métricos, Torx y Allen',
        'Llave dinamométrica',
        'Herramientas específicas KTM para el reglaje si hay que cambiar pastillas/taqués',
      ],
      parts: ['Junta de la tapa de balancines (si está dañada)', 'Pastillas de reglaje de la medida necesaria'],
      torques: [
        { part: 'Tornillos tapa de válvulas (M6)', nm: 10 },
        { part: 'Bujía interior (M12x1,5)', nm: 18 },
        { part: 'Bujía exterior (M10x1)', nm: 11 },
      ],
      steps: [
        'Con el motor frío (≈ 20 °C), desmonta filtro de aire y bujías.',
        'Desmonta las tapas de válvulas.',
        'Gira el cigüeñal hasta el punto muerto superior de compresión del cilindro que vayas a medir.',
        'Mide cada válvula con las galgas: admisión 0,10–0,15 mm, escape 0,25–0,30 mm.',
        'Anota todas las medidas. Si alguna está fuera de rango, hay que cambiar la pastilla de reglaje (trabajo de taller).',
        'Monta las tapas con juntas en buen estado y aprieta los tornillos M6 a 10 N·m.',
        'Monta bujías y filtro de aire.',
      ],
      tips: 'Es la revisión grande de los 30.000 km. Si no tienes experiencia con motores de distribución por cadena, déjala al taller.',
    },
    {
      id: 'sas',
      name: 'Membrana SAS (aire secundario)',
      category: 'motor',
      every: 30000,
      months: null,
      duration: '30 min',
      difficulty: 2,
      tools: ['Llaves Torx/Allen para la tapa de la válvula SAS', 'Llave dinamométrica de rango bajo'],
      parts: ['Membrana SAS nueva'],
      torques: [
        { part: 'Tornillos generales de motor (M5)', nm: 6 },
      ],
      steps: [
        'Localiza la válvula SAS (sistema de aire secundario) y desmonta su tapa.',
        'Sustituye la membrana por una nueva, respetando su posición.',
        'Comprueba que los manguitos del sistema no estén agrietados.',
        'Monta la tapa y aprieta los tornillos a su par.',
      ],
      tips: 'KTM pide cambiarla cada 30.000 km, coincidiendo con la revisión de válvulas.',
    },
    {
      id: 'cadena-engrasar',
      name: 'Cadena: limpiar y engrasar',
      category: 'transmision',
      every: 1000,
      months: null,
      duration: '20 min',
      difficulty: 1,
      tools: ['Caballete trasero', 'Limpiador de cadenas y cepillo', 'Spray de cadena para uso en carretera', 'Trapos'],
      parts: ['Limpiador y spray de cadena'],
      torques: [],
      steps: [
        'Sube la moto al caballete trasero y pon punto muerto.',
        'Quita la suciedad gruesa con agua y el limpiador de cadenas (compatible con retenes X-ring).',
        'Seca la cadena.',
        'Aplica el spray de cadena por la cara interior mientras giras la rueda.',
        'Retira el exceso: no debe llegar grasa al neumático ni al disco de freno.',
      ],
      tips: 'KTM indica limpiarla y engrasarla con regularidad según uso; cada 500–1.000 km o tras rodar en mojado es una buena referencia.',
    },
    {
      id: 'cadena-tensar',
      name: 'Cadena: tensión y desgaste',
      category: 'transmision',
      every: 15000,
      months: null,
      first: 1000,
      duration: '30 min',
      difficulty: 2,
      tools: [
        'Caballete trasero',
        'Llave de gancho KTM 61329085000 + mango 60012060000 (vienen en el juego de herramientas de la moto)',
        'Llave para el tornillo del excéntrico (M16)',
        'Llave dinamométrica (hasta 80 N·m)',
        'Metro y un peso o dinamómetro de 15 kg para medir el desgaste',
      ],
      parts: [],
      torques: [
        { part: 'Tornillo del excéntrico (tensor de cadena, M16)', nm: 70 },
        { part: 'Tuercas de la corona (M8)', nm: 36 },
        { part: 'Tornillos patín de cadena (M5)', nm: 5 },
      ],
      steps: [
        'Sube la moto al caballete trasero y pon punto muerto.',
        'En la zona del patín de cadena, empuja la cadena hacia arriba: el borde superior debe quedar entre las marcas A y B. El tramo inferior debe estar tenso.',
        'Repite la medida en varios puntos de la cadena (no se desgasta por igual).',
        'Si hay que ajustar: afloja el tornillo del excéntrico.',
        'Gira el buje excéntrico con la llave de gancho: en sentido horario tensas, en antihorario destensas.',
        'Vuelve a comprobar la tensión y aprieta el tornillo del excéntrico a 70 N·m.',
        'Desgaste: tirando del tramo inferior con 15 kg, la distancia de 18 rodillos no debe superar 272 mm.',
        'Revisa también piñón, corona y patín de cadena. Si hay que cambiar, cambia el kit completo (la cadena no lleva eslabón de cierre).',
      ],
      tips: 'La Super Duke usa basculante monobrazo con excéntrico: no hay tensores laterales ni hay que alinear la rueda.',
    },
    {
      id: 'frenos-revisar',
      name: 'Frenos: pastillas y discos',
      category: 'frenos',
      every: 15000,
      months: null,
      first: 1000,
      duration: '30 min',
      difficulty: 1,
      tools: ['Linterna', 'Calibre o regla (grosor de discos)', 'Llave dinamométrica (si hay que desmontar pinzas)'],
      parts: ['Pastillas de freno (si están por debajo de 1 mm)'],
      torques: [
        { part: 'Tornillos pinza de freno delantera (M10)', nm: 45, note: 'Loctite 243' },
        { part: 'Tornillos pinza de freno trasera (M8)', nm: 25, note: 'Loctite 2701' },
        { part: 'Tornillos disco delantero (M8)', nm: 30, note: 'Loctite 2701' },
        { part: 'Tornillos disco trasero (M8)', nm: 30, note: 'Loctite 243' },
        { part: 'Tornillo banjo latiguillo de freno (M10x1)', nm: 25 },
      ],
      steps: [
        'Mira el grosor de cada pastilla por el hueco de la pinza: mínimo 1 mm de material.',
        'Revisa que las pastillas no estén agrietadas ni dañadas.',
        'Mide el grosor de los discos: mínimo 4,5 mm delante y detrás.',
        'Revisa que los latiguillos no tengan grietas ni fugas.',
        'Comprueba el nivel de líquido en los depósitos de freno delantero, trasero y del embrague hidráulico.',
      ],
      tips: 'Si cambias pastillas, bombea la maneta/pedal antes de mover la moto hasta que los pistones vuelvan a su sitio.',
    },
    {
      id: 'liquido-frenos',
      name: 'Líquido de frenos y embrague',
      category: 'frenos',
      every: null,
      months: 24,
      duration: '1,5 h',
      difficulty: 3,
      tools: [
        'Llave para los purgadores',
        'Tubo transparente y botella',
        'Jeringuilla o purgador por vacío',
        'Trapos (el líquido daña la pintura)',
      ],
      parts: ['1 L de líquido DOT 4 / DOT 5.1 (frenos delantero, trasero y embrague hidráulico)'],
      torques: [
        { part: 'Tornillo banjo latiguillo de freno (M10x1)', nm: 25 },
        { part: 'Tornillo banjo, pieza de unión trasera (M10x1)', nm: 15 },
      ],
      steps: [
        'Protege pintura y plásticos: el líquido de frenos los ataca. Si cae, límpialo enseguida con agua.',
        'Abre el depósito del freno delantero y retira el líquido viejo.',
        'Rellena con líquido nuevo y purga pinza a pinza: abre el purgador, aprieta la maneta, cierra, suelta. Repite hasta que salga líquido limpio sin burbujas.',
        'No dejes que el depósito se vacíe durante la purga.',
        'Repite en el freno trasero y en el embrague hidráulico.',
        'Ajusta los niveles, monta las tapas con sus membranas y comprueba el tacto antes de rodar.',
      ],
      tips: 'La moto lleva ABS: si al purgar entra aire en la unidad ABS, el purgado completo requiere la herramienta de diagnosis del taller.',
    },
    {
      id: 'neumaticos',
      name: 'Neumáticos: estado y presión',
      category: 'chasis',
      every: 15000,
      months: null,
      first: 1000,
      duration: '10 min',
      difficulty: 1,
      tools: ['Manómetro', 'Compresor', 'Medidor de profundidad de dibujo'],
      parts: [],
      torques: [
        { part: 'Eje delantero (M25x1,5)', nm: 45, note: 'rosca engrasada' },
        { part: 'Tornillos de apriete del eje (M8)', nm: 15 },
        { part: 'Tuerca central rueda trasera (M50x1,5)', nm: 250, note: 'rosca engrasada + alambre de seguridad' },
      ],
      steps: [
        'Mide la presión en frío: 2,5 bar delante y 2,5 bar detrás (piloto solo).',
        'Revisa la profundidad del dibujo: mínimo legal y como mínimo 2 mm.',
        'Busca cortes, grietas, deformaciones o clavos.',
      ],
      tips: 'Revisa la presión cada dos semanas aunque no toque el mantenimiento: afecta mucho al comportamiento de la moto.',
    },
    {
      id: 'rueda-trasera',
      name: 'Rueda trasera: tuerca central',
      category: 'chasis',
      every: 15000,
      months: null,
      first: 1000,
      duration: '15 min',
      difficulty: 2,
      tools: [
        'Caballete trasero',
        'Vaso para la tuerca central (M50x1,5, de gran tamaño)',
        'Llave dinamométrica de alto rango (hasta 250 N·m)',
        'Alambre de seguridad y barniz de bloqueo',
      ],
      parts: ['Alambre de seguridad (si se ha desmontado)'],
      torques: [
        { part: 'Tuerca central rueda trasera (M50x1,5)', nm: 250, note: 'rosca engrasada + alambre de seguridad con barniz de bloqueo' },
        { part: 'Tuerca eje trasero, lado amortiguador (M35x1,5)', nm: 200, note: 'Loctite 262 + alambre de seguridad' },
      ],
      steps: [
        'Sube la moto al caballete trasero.',
        'Comprueba que el alambre de seguridad de la tuerca central (lado derecho) está intacto.',
        'Comprueba con la dinamométrica que la tuerca está apretada a 250 N·m.',
        'Si la has desmontado: engrasa la rosca, aprieta a 250 N·m y vuelve a poner el alambre de seguridad con barniz de bloqueo.',
      ],
      tips: 'Es un par muy alto: necesitas una dinamométrica grande y bloquear la rueda (freno trasero o ayudante).',
    },
    {
      id: 'buje-trasero',
      name: 'Rodamientos y engrase del buje trasero',
      category: 'chasis',
      every: 30000,
      months: null,
      duration: '2 h (taller)',
      difficulty: 4,
      tools: ['Caballete trasero', 'Vaso para la tuerca central', 'Llave dinamométrica de alto rango', 'Grasa de rodamientos'],
      parts: ['Grasa', 'Alambre de seguridad'],
      torques: [
        { part: 'Tuerca central rueda trasera (M50x1,5)', nm: 250, note: 'rosca engrasada + alambre de seguridad' },
        { part: 'Tuerca eje trasero, lado amortiguador (M35x1,5)', nm: 200, note: 'Loctite 262 + alambre de seguridad' },
      ],
      steps: [
        'Desmonta la rueda trasera.',
        'Mide la holgura de los rodamientos de rueda: no debe haber juego ni puntos duros al girar.',
        'Engrasa el buje trasero.',
        'Monta la rueda y aprieta la tuerca central a 250 N·m con la rosca engrasada; pon el alambre de seguridad.',
      ],
      tips: 'Trabajo recomendado para taller por los pares tan altos y el alambre de seguridad.',
    },
    {
      id: 'direccion-suspension',
      name: 'Dirección y suspensiones',
      category: 'chasis',
      every: 15000,
      months: null,
      first: 1000,
      duration: '30 min',
      difficulty: 2,
      tools: ['Caballete delantero o elevador', 'Llave dinamométrica', 'Trapo limpio'],
      parts: [],
      torques: [
        { part: 'Tornillos tija inferior (M8)', nm: 15 },
        { part: 'Tornillos tija superior (M8)', nm: 18 },
        { part: 'Tornillo superior pipa de dirección (M25x1,5)', nm: 18 },
        { part: 'Tornillos amortiguador superior e inferior (M14x1,5)', nm: 80, note: 'rosca engrasada' },
        { part: 'Tuerca eje del basculante (M19x1,5)', nm: 130, note: 'rosca engrasada' },
      ],
      steps: [
        'Con la rueda delantera en el aire, mueve la horquilla adelante y atrás: no debe haber holgura en la pipa.',
        'Gira el manillar de tope a tope: debe ir suave, sin puntos duros.',
        'Revisa que horquilla y amortiguador no pierdan aceite.',
        'Limpia los guardapolvos de las barras de la horquilla (cada 15.000 km).',
      ],
      tips: 'El servicio completo de horquilla y amortiguador se hace según uso: si notas pérdidas o la suspensión ha cambiado de tacto, llévala a un especialista WP.',
    },
    {
      id: 'refrigerante',
      name: 'Refrigerante: sustituir',
      category: 'refrigeracion',
      every: null,
      months: 48,
      duration: '1 h',
      difficulty: 3,
      tools: ['Bandeja', 'Embudo', 'Llave dinamométrica de rango bajo'],
      parts: ['3,2 L de refrigerante'],
      torques: [
        { part: 'Tornillo de purga, tapa bomba de agua (M6)', nm: 10 },
      ],
      steps: [
        'Hazlo siempre con el motor frío: el sistema está a presión y el líquido quema.',
        'Vacía el circuito según el manual y recoge el refrigerante (es tóxico).',
        'Rellena con refrigerante nuevo y purga el aire del circuito.',
        'Arranca, deja que se caliente y comprueba que el ventilador se activa.',
        'Con el motor frío, el nivel del vaso de expansión debe quedar entre MIN y MAX.',
      ],
      tips: 'En cada revisión comprueba el nivel del vaso de expansión con el motor frío y la protección del anticongelante.',
    },
    {
      id: 'engrase-tornilleria',
      name: 'Engrase y tornillería',
      category: 'chasis',
      every: 15000,
      months: 12,
      first: 1000,
      duration: '45 min',
      difficulty: 1,
      tools: ['Juego de llaves y vasos métricos, Torx y Allen', 'Llave dinamométrica', 'Grasa y spray lubricante'],
      parts: ['Grasa'],
      torques: [
        { part: 'Tornillos generales de chasis M6', nm: 10 },
        { part: 'Tornillos generales de chasis M8', nm: 25 },
        { part: 'Tornillos generales de chasis M10', nm: 45 },
        { part: 'Tornillos abrazadera del manillar (M8)', nm: 20 },
        { part: 'Tornillo del caballete lateral (M10)', nm: 35, note: 'Loctite 243' },
      ],
      steps: [
        'Engrasa las piezas móviles: caballete lateral, manetas, articulaciones de pedales.',
        'Vacía los tubos de drenaje.',
        'Revisa manguitos de gasolina, refrigeración y respiraderos: sin grietas, fugas ni pliegues.',
        'Comprueba el apriete de tornillos y tuercas accesibles con sus pares.',
      ],
      tips: 'KTM lo marca como trabajo recomendado en cada revisión y al menos una vez al año.',
    },
    {
      id: 'diagnosis',
      name: 'Diagnosis y válvula de escape (taller)',
      category: 'electrico',
      every: 15000,
      months: 12,
      first: 1000,
      duration: '30 min (taller)',
      difficulty: 5,
      tools: ['Herramienta de diagnosis KTM (sólo concesionario/taller)'],
      parts: [],
      torques: [],
      steps: [
        'Leer y borrar la memoria de errores con la herramienta de diagnosis KTM.',
        'Comprobar el control de la válvula de escape.',
        'Comprobar el ajuste de CO y el funcionamiento del ventilador.',
        'Resetear el indicador de servicio del cuadro.',
      ],
      tips: 'Sin la herramienta de diagnosis no se puede resetear el aviso de servicio: pídelo en el taller en la revisión anual.',
    },
    {
      id: 'bateria',
      name: 'Batería: revisar',
      category: 'electrico',
      every: null,
      months: 12,
      duration: '10 min',
      difficulty: 1,
      tools: ['Polímetro', 'Llave para los bornes', 'Llave dinamométrica de rango bajo'],
      parts: ['Batería YTX14-BS (si hay que cambiarla)'],
      torques: [
        { part: 'Tornillos bornes de batería (M6)', nm: 4.5 },
      ],
      steps: [
        'Mide la tensión con la moto apagada: 12,6 V o más = cargada; menos de 12,4 V = cárgala.',
        'Con el motor a unas 5.000 rpm debe marcar entre 13,5 y 15 V.',
        'Limpia y protege los bornes si hay sulfato. Apriétalos a 4,5 N·m.',
      ],
      tips: 'La electrónica de la Super Duke consume algo incluso apagada: si no la usas en semanas, conecta un mantenedor de carga.',
    },
  ],
});
