// Datos técnicos de la Yamaha YZF-R6 (2004, modelo 5SL).
// Plan de mantenimiento europeo y capacidades del manual de usuario Yamaha 5SL-28199-E2;
// pares de apriete y holguras del manual de servicio Yamaha YZF-R6 5SL (2003-2004).
// Verifica siempre los valores críticos con el manual de taller de tu unidad.

BIKES.push({
  id: 'yzfr6',
  brand: 'yamaha',
  short: 'YZF-R6',
  name: 'Yamaha YZF-R6',
  years: '2004',
  unit: 'km',
  before: 500,
  source: 'el manual de usuario Yamaha YZF-R6 5SL (plan europeo) y el manual de servicio 5SL (pares y holguras)',
  specs: [
    { label: 'Motor', value: '4 cilindros en línea 600 cc, DOHC, refrigeración líquida, inyección' },
    { label: 'Aceite motor', value: 'SAE 10W-40 (o 10W-30, 15W-40, 20W-40, 20W-50 según temperatura) · API SE/SF/SG o superior' },
    { label: 'Capacidad aceite', value: '2,4 L (cambio) · 2,6 L (con filtro)' },
    { label: 'Bujías', value: 'NGK CR9EK o CR10EK (4) · distancia 0,6–0,7 mm' },
    { label: 'Holgura válvulas (en frío)', value: 'Admisión 0,13–0,20 mm · Escape 0,23–0,30 mm' },
    { label: 'Refrigerante', value: '2,15 L (circuito) + 0,25 L (vaso de expansión)' },
    { label: 'Líquido de frenos', value: 'DOT 4' },
    { label: 'Filtro de aire', value: 'Elemento de tipo húmedo (no se lava: se revisa y se cambia)' },
    { label: 'Holgura cadena', value: '35–45 mm' },
    { label: 'Transmisión secundaria', value: '16:48' },
    { label: 'Neumáticos', value: '120/70 ZR17 · 180/55 ZR17' },
    { label: 'Presión neumáticos', value: 'Delantero 2,5 bar · Trasero 2,9 bar (en frío, con cualquier carga)' },
    { label: 'Frenos: límites', value: 'Pastillas del. mín. 0,5 mm · tras. mín. 1,0 mm · Discos mín. 4,5 mm' },
    { label: 'Batería', value: 'GT9B-4 · 12 V 8 Ah' },
    { label: 'Depósito', value: '17 L (reserva 3,5 L)' },
  ],
  tasks: [
    {
      id: 'aceite',
      name: 'Cambio de aceite motor',
      category: 'motor',
      every: 10000,
      months: 12,
      first: 1000,
      duration: '30 min',
      difficulty: 1,
      tools: [
        'Llave para el tornillo de vaciado (M14)',
        'Llave dinamométrica (rango 10–60 N·m)',
        'Bandeja de vaciado (mín. 3 L)',
        'Embudo, guantes y trapos',
      ],
      parts: ['2,4 L de aceite SAE 10W-40 API SG o superior (2,6 L si cambias filtro)', 'Junta nueva del tornillo de vaciado'],
      torques: [
        { part: 'Tornillo de vaciado de aceite (M14)', nm: 43 },
      ],
      steps: [
        'Calienta el motor unos minutos y apágalo.',
        'Pon la moto recta (caballete trasero) y la bandeja debajo. Quita el tapón de llenado.',
        'Quita el tornillo de vaciado y deja escurrir el aceite.',
        'Si toca, cambia ahora el filtro (ver "Filtro de aceite").',
        'Monta el tornillo de vaciado con junta nueva y apriétalo a 43 N·m.',
        'Echa 2,4 L de aceite (2,6 L si has cambiado el filtro) y cierra el tapón.',
        'Arranca unos minutos y revisa que no haya fugas.',
        'Apaga, espera unos minutos y comprueba el nivel en la mirilla con la moto recta: entre las marcas de mínimo y máximo.',
      ],
      tips: 'Si se enciende el testigo de nivel de aceite con el motor en marcha, para y revisa el nivel enseguida.',
    },
    {
      id: 'filtro-aceite',
      name: 'Cambio filtro de aceite',
      category: 'motor',
      every: 20000,
      months: null,
      first: 1000,
      duration: '15 min (junto con el aceite)',
      difficulty: 1,
      tools: ['Llave de filtro de aceite (Yamaha 90890-01426 o equivalente)', 'Llave dinamométrica', 'Trapos'],
      parts: ['Filtro de aceite (cartucho)'],
      torques: [
        { part: 'Filtro de aceite (cartucho)', nm: 17 },
      ],
      steps: [
        'Hazlo con el aceite ya vaciado.',
        'Quita el filtro con la llave de filtro. Pon trapos debajo: gotea.',
        'Unta la junta tórica del filtro nuevo con un poco de aceite limpio y comprueba que está bien asentada en su ranura.',
        'Enrosca el filtro y apriétalo a 17 N·m con la llave de filtro.',
        'Rellena 2,6 L de aceite y comprueba el nivel y las fugas.',
      ],
      tips: 'El filtro es barato: mucha gente lo cambia en cada cambio de aceite.',
    },
    {
      id: 'filtro-aire-revisar',
      name: 'Filtro de aire: revisar',
      category: 'motor',
      every: 10000,
      months: null,
      duration: '30 min',
      difficulty: 2,
      tools: ['Llaves para los tornillos del depósito', 'Destornillador para la tapa de la caja del filtro'],
      parts: [],
      torques: [],
      steps: [
        'Quita el asiento del piloto y los tornillos delanteros del depósito.',
        'Levanta la parte delantera del depósito y apóyalo hacia atrás, bien sujeto. No desconectes los tubos de gasolina.',
        'Quita la tapa de la caja del filtro y saca el filtro.',
        'Revísalo: si está dañado o muy sucio, cámbialo. Es de tipo húmedo: no lo laves.',
        'Colócalo bien asentado en la caja, monta la tapa y vuelve a colocar el depósito.',
      ],
      tips: 'Si ruedas con lluvia o polvo, revísalo más a menudo. Nunca arranques sin filtro.',
    },
    {
      id: 'filtro-aire-cambiar',
      name: 'Filtro de aire: sustituir',
      category: 'motor',
      every: 20000,
      months: null,
      resets: ['filtro-aire-revisar'],
      duration: '30 min',
      difficulty: 2,
      tools: ['Llaves para los tornillos del depósito', 'Destornillador'],
      parts: ['Filtro de aire'],
      torques: [],
      steps: [
        'Quita el asiento, suelta el depósito por delante y apóyalo hacia atrás sin desconectar los tubos.',
        'Quita la tapa de la caja del filtro y cambia el filtro.',
        'Comprueba que el filtro nuevo asienta bien en todo el contorno.',
        'Monta la tapa y el depósito.',
      ],
      tips: 'Aprovecha para cambiar las bujías: también tocan a los 20.000 km y se accede por el mismo sitio.',
    },
    {
      id: 'bujias-revisar',
      name: 'Bujías: revisar',
      category: 'electrico',
      every: 10000,
      months: null,
      duration: '1 h',
      difficulty: 3,
      tools: ['Llave de bujías de pared fina', 'Alargo', 'Galgas de espesores', 'Llave dinamométrica'],
      parts: [],
      torques: [
        { part: 'Bujías (M10)', nm: 13 },
      ],
      steps: [
        'Con el motor frío, quita asiento, depósito y caja del filtro de aire.',
        'Sopla alrededor de las bujías, quita las pipas y saca las 4 bujías.',
        'El aislante debe ser marrón claro. Limpia y ajusta la distancia entre electrodos a 0,6–0,7 mm.',
        'Limpia la bujía y la superficie de la junta, enrosca a mano y aprieta a 13 N·m.',
        'Monta las pipas, la caja del filtro, el depósito y el asiento.',
      ],
      tips: 'Una bujía con el aislante muy distinto al resto indica un problema en ese cilindro: llévala a revisar.',
    },
    {
      id: 'bujias-cambiar',
      name: 'Bujías: sustituir',
      category: 'electrico',
      every: 20000,
      months: null,
      resets: ['bujias-revisar'],
      duration: '1 h',
      difficulty: 3,
      tools: ['Llave de bujías de pared fina', 'Alargo', 'Galgas de espesores', 'Llave dinamométrica'],
      parts: ['4 bujías NGK CR9EK o CR10EK'],
      torques: [
        { part: 'Bujías (M10)', nm: 13 },
      ],
      steps: [
        'Con el motor frío, quita asiento, depósito y caja del filtro de aire.',
        'Sopla alrededor de las bujías y sácalas.',
        'Comprueba la distancia entre electrodos de las nuevas: 0,6–0,7 mm.',
        'Enrosca a mano hasta el tope y aprieta a 13 N·m.',
        'Monta pipas, caja del filtro, depósito y asiento.',
      ],
      tips: 'La CR10EK es más fría: para uso en circuito o muy deportivo.',
    },
    {
      id: 'valvulas',
      name: 'Holgura de válvulas',
      category: 'motor',
      every: 40000,
      months: null,
      duration: '5–6 h (taller)',
      difficulty: 5,
      tools: ['Galgas de espesores', 'Juego de llaves y vasos métricos', 'Llave dinamométrica'],
      parts: ['Junta de la tapa de culata', 'Pastillas de reglaje de la medida necesaria'],
      torques: [
        { part: 'Bujías (M10)', nm: 13 },
      ],
      steps: [
        'Con el motor frío, desmonta asiento, depósito, caja del filtro, bujías y tapa de culata.',
        'Pon cada cilindro en el punto muerto superior de compresión.',
        'Mide cada válvula: admisión 0,13–0,20 mm, escape 0,23–0,30 mm.',
        'Si alguna está fuera de rango, se corrige cambiando la pastilla de reglaje (trabajo de taller).',
        'Monta la tapa de culata con junta nueva si hace falta y el resto de piezas.',
      ],
      tips: 'Son 16 válvulas: anota todas las medidas para ver cómo evolucionan.',
    },
    {
      id: 'inyeccion',
      name: 'Inyección: ralentí y sincronización',
      category: 'motor',
      every: 10000,
      months: 12,
      first: 1000,
      duration: '1 h (taller)',
      difficulty: 4,
      tools: ['Vacuómetros para sincronizar las mariposas', 'Herramientas de diagnosis'],
      parts: [],
      torques: [],
      steps: [
        'Con el motor caliente, ajusta el ralentí.',
        'Sincroniza los cuerpos de inyección con los vacuómetros.',
        'Revisa el sistema de inducción de aire (válvula de corte, láminas y manguitos).',
      ],
      tips: 'Una mala sincronización se nota en tirones y vibraciones a bajas vueltas.',
    },
    {
      id: 'embrague-cables',
      name: 'Embrague, cables y mandos',
      category: 'transmision',
      every: 10000,
      months: 12,
      first: 1000,
      duration: '20 min',
      difficulty: 1,
      tools: ['Llaves para los tensores de los cables', 'Spray lubricante para cables'],
      parts: [],
      torques: [],
      steps: [
        'Comprueba el funcionamiento del embrague y el juego libre de la maneta; ajústalo si hace falta.',
        'Comprueba el juego libre del puño del gas y ajústalo.',
        'Lubrica el puño del gas, los cables y las articulaciones de manetas y pedales.',
        'Comprueba los interruptores de freno delantero y trasero.',
      ],
      tips: 'Un cable duro o con tirones suele ser falta de lubricación.',
    },
    {
      id: 'cadena',
      name: 'Cadena: holgura y engrase',
      category: 'transmision',
      every: 800,
      months: null,
      duration: '20 min',
      difficulty: 2,
      tools: [
        'Caballete trasero',
        'Llave para la tuerca del eje trasero (M24)',
        'Llaves para contratuercas y tensores',
        'Llave dinamométrica (hasta 120 N·m)',
        'Spray de cadena para juntas tóricas',
      ],
      parts: ['Spray de cadena'],
      torques: [
        { part: 'Tuerca del eje trasero (M24)', nm: 110 },
        { part: 'Tuercas de la corona (M10)', nm: 100 },
      ],
      steps: [
        'Mide la holgura de la cadena: 35–45 mm.',
        'Para ajustar: afloja la tuerca del eje trasero y las contratuercas de los tensores.',
        'Gira los tensores por igual en ambos lados hasta la holgura correcta, con las marcas de alineación iguales a los dos lados.',
        'Aprieta las contratuercas y la tuerca del eje a 110 N·m.',
        'Limpia la cadena y engrásala con un lubricante especial para cadenas con juntas tóricas.',
      ],
      tips: 'Yamaha pide revisarla y engrasarla cada 800 km y siempre después de lavar la moto o rodar con lluvia.',
    },
    {
      id: 'frenos-revisar',
      name: 'Frenos: pastillas, discos y líquido',
      category: 'frenos',
      every: 10000,
      months: 12,
      first: 1000,
      duration: '30 min',
      difficulty: 1,
      tools: ['Linterna', 'Calibre', 'Llave dinamométrica (si hay que desmontar)'],
      parts: ['Pastillas de freno (si están en el límite)'],
      torques: [
        { part: 'Tornillos pinza de freno delantera (M10)', nm: 40 },
        { part: 'Tornillos disco delantero (M6)', nm: 18 },
        { part: 'Tornillos disco trasero (M8)', nm: 30 },
        { part: 'Tornillo banjo latiguillo trasero (M10)', nm: 30 },
        { part: 'Purgadores de las pinzas (M8)', nm: 6 },
      ],
      steps: [
        'Revisa las pastillas: mínimo 0,5 mm delante y 1,0 mm detrás. Cámbialas si llegan al límite.',
        'Mide los discos: mínimo 4,5 mm delante y detrás.',
        'Comprueba el nivel de líquido y que no haya fugas.',
        'Revisa los latiguillos: sin grietas ni daños.',
      ],
      tips: 'Tras cambiar pastillas, bombea la maneta antes de mover la moto.',
    },
    {
      id: 'liquido-frenos',
      name: 'Líquido de frenos y juntas de bombas',
      category: 'frenos',
      every: null,
      months: 24,
      duration: '1–2 h',
      difficulty: 3,
      tools: ['Llave para los purgadores', 'Tubo transparente y botella', 'Trapos'],
      parts: ['Líquido de frenos DOT 4', 'Kits de reparación de bombas y pinzas (juntas y retenes)'],
      torques: [
        { part: 'Purgadores de las pinzas (M8)', nm: 6 },
      ],
      steps: [
        'Protege la pintura y los plásticos del líquido de frenos.',
        'Cambia el líquido y purga cada pinza hasta que salga limpio y sin burbujas.',
        'Yamaha pide también cambiar cada 2 años los componentes internos (juntas) de bombas y pinzas.',
        'Comprueba el tacto antes de rodar.',
      ],
      tips: 'El cambio de juntas de bombas y pinzas es trabajo de taller si no tienes experiencia.',
    },
    {
      id: 'latiguillos',
      name: 'Latiguillos de freno',
      category: 'frenos',
      every: null,
      months: 48,
      duration: '1,5 h',
      difficulty: 3,
      tools: ['Llaves', 'Llave dinamométrica', 'Material para purgar'],
      parts: ['Latiguillos de freno', 'Arandelas de cobre nuevas', 'Líquido DOT 4'],
      torques: [
        { part: 'Tornillo banjo latiguillo trasero (M10)', nm: 30 },
      ],
      steps: [
        'Sustituye los latiguillos con arandelas nuevas.',
        'Rellena con DOT 4 y purga.',
        'Comprueba el tacto antes de rodar.',
      ],
      tips: 'Yamaha pide cambiarlos cada 4 años o antes si tienen grietas.',
    },
    {
      id: 'ruedas-neumaticos',
      name: 'Ruedas, neumáticos y rodamientos',
      category: 'chasis',
      every: 10000,
      months: 12,
      duration: '20 min',
      difficulty: 1,
      tools: ['Manómetro', 'Medidor de profundidad', 'Caballetes'],
      parts: [],
      torques: [
        { part: 'Eje delantero (M14)', nm: 91 },
        { part: 'Tornillos de apriete del eje delantero (M8)', nm: 18, note: 'aprieta, alinea la botella izquierda con el eje y vuelve a apretar' },
        { part: 'Tuerca del eje trasero (M24)', nm: 110 },
      ],
      steps: [
        'Mide la presión en frío: 2,5 bar delante y 2,9 bar detrás.',
        'Revisa el dibujo y busca cortes o deformaciones.',
        'Comprueba que las llantas no estén golpeadas ni descentradas.',
        'Con cada rueda en el aire, muévela lateralmente: no debe haber holgura en los rodamientos.',
      ],
      tips: 'Revisa la presión cada dos semanas aunque no toque el mantenimiento.',
    },
    {
      id: 'direccion-suspension',
      name: 'Dirección, basculante y suspensiones',
      category: 'chasis',
      every: 10000,
      months: null,
      first: 1000,
      duration: '45 min',
      difficulty: 2,
      tools: ['Caballetes', 'Llave dinamométrica', 'Grasa de litio'],
      parts: [],
      torques: [
        { part: 'Semimanillares a la horquilla (M8)', nm: 33 },
        { part: 'Semimanillares a la tija superior (M6)', nm: 13 },
      ],
      steps: [
        'Con la rueda delantera en el aire, comprueba que la dirección gira suave y sin holgura.',
        'Mueve el basculante lateralmente: no debe tener holgura.',
        'Revisa que horquilla y amortiguador no pierdan aceite y funcionen bien.',
        'Comprueba las articulaciones de las bieletas de la suspensión trasera.',
      ],
      tips: 'Yamaha pide engrasar los rodamientos de dirección cada 20.000 km y el basculante cada 50.000 km (taller).',
    },
    {
      id: 'refrigerante',
      name: 'Refrigerante: sustituir',
      category: 'refrigeracion',
      every: null,
      months: 36,
      duration: '1 h',
      difficulty: 3,
      tools: ['Bandeja', 'Embudo'],
      parts: ['2,4 L de refrigerante'],
      torques: [],
      steps: [
        'Con el motor frío, vacía el circuito por los tornillos de vaciado (con arandelas de cobre nuevas al montar).',
        'Rellena el radiador y el vaso de expansión con refrigerante nuevo.',
        'Arranca, purga el aire y vuelve a comprobar el nivel en frío: entre las marcas del vaso.',
      ],
      tips: 'En cada revisión comprueba el nivel del vaso de expansión con la moto recta y el motor frío.',
    },
    {
      id: 'tornilleria-escape',
      name: 'Tornillería, escape y caballete',
      category: 'chasis',
      every: 10000,
      months: 12,
      first: 1000,
      duration: '30 min',
      difficulty: 1,
      tools: ['Juego de llaves y vasos métricos', 'Llave dinamométrica', 'Grasa'],
      parts: [],
      torques: [
        { part: 'Soporte del caballete lateral al chasis (M10)', nm: 61 },
      ],
      steps: [
        'Comprueba el apriete de tuercas, tornillos y abrazaderas del chasis.',
        'Revisa el escape: sin fugas y bien sujeto.',
        'Engrasa el caballete lateral y comprueba su interruptor de seguridad.',
        'Revisa los manguitos de gasolina y respiradero del cárter.',
      ],
      tips: 'Comprueba también luces, intermitentes y claxon.',
    },
    {
      id: 'bateria',
      name: 'Batería: revisar',
      category: 'electrico',
      every: null,
      months: 12,
      duration: '10 min',
      difficulty: 1,
      tools: ['Polímetro', 'Llave para los bornes'],
      parts: ['Batería GT9B-4 (si hay que cambiarla)'],
      torques: [],
      steps: [
        'Mide la tensión con la moto apagada: 12,6 V o más = cargada; menos de 12,4 V = cárgala.',
        'Con el motor a unas 5.000 rpm debe marcar entre 13,5 y 15 V.',
        'Limpia y protege los bornes si hay sulfato.',
      ],
      tips: 'Si no la usas en invierno, conéctala a un mantenedor de carga.',
    },
  ],
});
